/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.jooq.tables.records;


import javax.annotation.Generated;

import kr.pe.codda.jooq.tables.SbBoardFilelistTb;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbBoardFilelistTbRecord extends UpdatableRecordImpl<SbBoardFilelistTbRecord> implements Record5<UByte, UInteger, UByte, String, Long> {

    private static final long serialVersionUID = 837501387;

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.board_id</code>.
     */
    public void setBoardId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.board_id</code>.
     */
    public UByte getBoardId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.board_no</code>.
     */
    public void setBoardNo(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.board_no</code>.
     */
    public UInteger getBoardNo() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.attached_file_sq</code>. 첨부 파일 순번
     */
    public void setAttachedFileSq(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.attached_file_sq</code>. 첨부 파일 순번
     */
    public UByte getAttachedFileSq() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.attached_fname</code>. 첨부 파일 이름
     */
    public void setAttachedFname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.attached_fname</code>. 첨부 파일 이름
     */
    public String getAttachedFname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.attached_fsize</code>. 첨부 파일 크기
     */
    public void setAttachedFsize(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.attached_fsize</code>. 첨부 파일 크기
     */
    public Long getAttachedFsize() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<UByte, UInteger, UByte> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UByte, UInteger, UByte, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UByte, UInteger, UByte, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.BOARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.BOARD_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACHED_FILE_SQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACHED_FNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACHED_FSIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getBoardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getBoardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getAttachedFileSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAttachedFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getAttachedFsize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getBoardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getBoardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getAttachedFileSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAttachedFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getAttachedFsize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value1(UByte value) {
        setBoardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value2(UInteger value) {
        setBoardNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value3(UByte value) {
        setAttachedFileSq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value4(String value) {
        setAttachedFname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value5(Long value) {
        setAttachedFsize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord values(UByte value1, UInteger value2, UByte value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbBoardFilelistTbRecord
     */
    public SbBoardFilelistTbRecord() {
        super(SbBoardFilelistTb.SB_BOARD_FILELIST_TB);
    }

    /**
     * Create a detached, initialised SbBoardFilelistTbRecord
     */
    public SbBoardFilelistTbRecord(UByte boardId, UInteger boardNo, UByte attachedFileSq, String attachedFname, Long attachedFsize) {
        super(SbBoardFilelistTb.SB_BOARD_FILELIST_TB);

        set(0, boardId);
        set(1, boardNo);
        set(2, attachedFileSq);
        set(3, attachedFname);
        set(4, attachedFsize);
    }
}
