/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.jooq.tables.records;


import javax.annotation.Generated;

import kr.pe.codda.jooq.tables.SbSitemenuTb;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbSitemenuTbRecord extends UpdatableRecordImpl<SbSitemenuTbRecord> implements Record6<UInteger, UInteger, UByte, UByte, String, String> {

    private static final long serialVersionUID = 1677913799;

    /**
     * Setter for <code>sb_db.sb_sitemenu_tb.menu_no</code>. 메뉴 번호,  1부터 시작된다. 1 로 초기화 되는 시퀀스 테이블(SB_SEQ_TB) 로 부터 메뉴 번호를 얻어옴.
     */
    public void setMenuNo(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_sitemenu_tb.menu_no</code>. 메뉴 번호,  1부터 시작된다. 1 로 초기화 되는 시퀀스 테이블(SB_SEQ_TB) 로 부터 메뉴 번호를 얻어옴.
     */
    public UInteger getMenuNo() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_sitemenu_tb.parent_no</code>. 부모 메뉴 번호,  메뉴 번호는 1부터 시작되며 부모가 없는 경우 부모 메뉴 번호 값은  0 값을 갖는다.
     */
    public void setParentNo(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_sitemenu_tb.parent_no</code>. 부모 메뉴 번호,  메뉴 번호는 1부터 시작되며 부모가 없는 경우 부모 메뉴 번호 값은  0 값을 갖는다.
     */
    public UInteger getParentNo() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_sitemenu_tb.depth</code>. 트리 깊이,  0 부터 시작하며 부모보다 + 1 이 크다
     */
    public void setDepth(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_sitemenu_tb.depth</code>. 트리 깊이,  0 부터 시작하며 부모보다 + 1 이 크다
     */
    public UByte getDepth() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>sb_db.sb_sitemenu_tb.order_sq</code>. 전체 메뉴 순서
     */
    public void setOrderSq(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>sb_db.sb_sitemenu_tb.order_sq</code>. 전체 메뉴 순서
     */
    public UByte getOrderSq() {
        return (UByte) get(3);
    }

    /**
     * Setter for <code>sb_db.sb_sitemenu_tb.menu_nm</code>. 메뉴 이름
     */
    public void setMenuNm(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sb_db.sb_sitemenu_tb.menu_nm</code>. 메뉴 이름
     */
    public String getMenuNm() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sb_db.sb_sitemenu_tb.link_url</code>. 메뉴에 대응되는 링크 주소
     */
    public void setLinkUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sb_db.sb_sitemenu_tb.link_url</code>. 메뉴에 대응되는 링크 주소
     */
    public String getLinkUrl() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, UByte, UByte, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, UByte, UByte, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return SbSitemenuTb.SB_SITEMENU_TB.MENU_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbSitemenuTb.SB_SITEMENU_TB.PARENT_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return SbSitemenuTb.SB_SITEMENU_TB.DEPTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field4() {
        return SbSitemenuTb.SB_SITEMENU_TB.ORDER_SQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SbSitemenuTb.SB_SITEMENU_TB.MENU_NM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SbSitemenuTb.SB_SITEMENU_TB.LINK_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getMenuNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getParentNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getDepth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component4() {
        return getOrderSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMenuNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLinkUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getMenuNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getParentNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getDepth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value4() {
        return getOrderSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMenuNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLinkUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSitemenuTbRecord value1(UInteger value) {
        setMenuNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSitemenuTbRecord value2(UInteger value) {
        setParentNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSitemenuTbRecord value3(UByte value) {
        setDepth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSitemenuTbRecord value4(UByte value) {
        setOrderSq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSitemenuTbRecord value5(String value) {
        setMenuNm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSitemenuTbRecord value6(String value) {
        setLinkUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSitemenuTbRecord values(UInteger value1, UInteger value2, UByte value3, UByte value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbSitemenuTbRecord
     */
    public SbSitemenuTbRecord() {
        super(SbSitemenuTb.SB_SITEMENU_TB);
    }

    /**
     * Create a detached, initialised SbSitemenuTbRecord
     */
    public SbSitemenuTbRecord(UInteger menuNo, UInteger parentNo, UByte depth, UByte orderSq, String menuNm, String linkUrl) {
        super(SbSitemenuTb.SB_SITEMENU_TB);

        set(0, menuNo);
        set(1, parentNo);
        set(2, depth);
        set(3, orderSq);
        set(4, menuNm);
        set(5, linkUrl);
    }
}
