/*
 * This file is generated by jOOQ.
*/
package kr.pe.sinnori.impl.jooq;


import javax.annotation.Generated;

import kr.pe.sinnori.impl.jooq.tables.OaMemberTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardFileinfoTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardFilelistTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardInfoTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardVoteTb;
import kr.pe.sinnori.impl.jooq.tables.SbGroupInfoTb;
import kr.pe.sinnori.impl.jooq.tables.SbGroupTb;
import kr.pe.sinnori.impl.jooq.tables.SbMemberTb;
import kr.pe.sinnori.impl.jooq.tables.SbSeqTb;
import kr.pe.sinnori.impl.jooq.tables.records.OaMemberTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardFileinfoTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardFilelistTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardInfoTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardVoteTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbGroupInfoTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbGroupTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbMemberTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbSeqTbRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>SB_DB</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<SbBoardFileinfoTbRecord, UInteger> IDENTITY_SB_BOARD_FILEINFO_TB = Identities0.IDENTITY_SB_BOARD_FILEINFO_TB;
    public static final Identity<SbBoardTbRecord, UInteger> IDENTITY_SB_BOARD_TB = Identities0.IDENTITY_SB_BOARD_TB;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OaMemberTbRecord> KEY_OA_MEMBER_TB_PRIMARY = UniqueKeys0.KEY_OA_MEMBER_TB_PRIMARY;
    public static final UniqueKey<SbBoardFileinfoTbRecord> KEY_SB_BOARD_FILEINFO_TB_PRIMARY = UniqueKeys0.KEY_SB_BOARD_FILEINFO_TB_PRIMARY;
    public static final UniqueKey<SbBoardFilelistTbRecord> KEY_SB_BOARD_FILELIST_TB_PRIMARY = UniqueKeys0.KEY_SB_BOARD_FILELIST_TB_PRIMARY;
    public static final UniqueKey<SbBoardInfoTbRecord> KEY_SB_BOARD_INFO_TB_PRIMARY = UniqueKeys0.KEY_SB_BOARD_INFO_TB_PRIMARY;
    public static final UniqueKey<SbBoardTbRecord> KEY_SB_BOARD_TB_PRIMARY = UniqueKeys0.KEY_SB_BOARD_TB_PRIMARY;
    public static final UniqueKey<SbBoardVoteTbRecord> KEY_SB_BOARD_VOTE_TB_PRIMARY = UniqueKeys0.KEY_SB_BOARD_VOTE_TB_PRIMARY;
    public static final UniqueKey<SbGroupInfoTbRecord> KEY_SB_GROUP_INFO_TB_PRIMARY = UniqueKeys0.KEY_SB_GROUP_INFO_TB_PRIMARY;
    public static final UniqueKey<SbGroupTbRecord> KEY_SB_GROUP_TB_PRIMARY = UniqueKeys0.KEY_SB_GROUP_TB_PRIMARY;
    public static final UniqueKey<SbMemberTbRecord> KEY_SB_MEMBER_TB_PRIMARY = UniqueKeys0.KEY_SB_MEMBER_TB_PRIMARY;
    public static final UniqueKey<SbMemberTbRecord> KEY_SB_MEMBER_TB_SB_MEMBER_IDX1 = UniqueKeys0.KEY_SB_MEMBER_TB_SB_MEMBER_IDX1;
    public static final UniqueKey<SbSeqTbRecord> KEY_SB_SEQ_TB_PRIMARY = UniqueKeys0.KEY_SB_SEQ_TB_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SbBoardFileinfoTbRecord, SbMemberTbRecord> SB_BOARD_FILEINFO_FK1 = ForeignKeys0.SB_BOARD_FILEINFO_FK1;
    public static final ForeignKey<SbBoardFilelistTbRecord, SbBoardFileinfoTbRecord> SB_BOARD_FILELIST_FK1 = ForeignKeys0.SB_BOARD_FILELIST_FK1;
    public static final ForeignKey<SbBoardTbRecord, SbBoardInfoTbRecord> SB_BOARD_FK1 = ForeignKeys0.SB_BOARD_FK1;
    public static final ForeignKey<SbBoardTbRecord, SbMemberTbRecord> SB_BOARD_FK2 = ForeignKeys0.SB_BOARD_FK2;
    public static final ForeignKey<SbBoardTbRecord, SbBoardFileinfoTbRecord> SB_BOARD_FK3 = ForeignKeys0.SB_BOARD_FK3;
    public static final ForeignKey<SbBoardVoteTbRecord, SbBoardTbRecord> SB_BOARD_VOTE_FK1 = ForeignKeys0.SB_BOARD_VOTE_FK1;
    public static final ForeignKey<SbBoardVoteTbRecord, SbMemberTbRecord> SB_BOARD_VOTE_FK2 = ForeignKeys0.SB_BOARD_VOTE_FK2;
    public static final ForeignKey<SbGroupTbRecord, SbGroupInfoTbRecord> SB_GROUP_FK1 = ForeignKeys0.SB_GROUP_FK1;
    public static final ForeignKey<SbGroupTbRecord, SbMemberTbRecord> SB_GROUP_FK2 = ForeignKeys0.SB_GROUP_FK2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<SbBoardFileinfoTbRecord, UInteger> IDENTITY_SB_BOARD_FILEINFO_TB = Internal.createIdentity(SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB, SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB.ATTACH_ID);
        public static Identity<SbBoardTbRecord, UInteger> IDENTITY_SB_BOARD_TB = Internal.createIdentity(SbBoardTb.SB_BOARD_TB, SbBoardTb.SB_BOARD_TB.BOARD_NO);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<OaMemberTbRecord> KEY_OA_MEMBER_TB_PRIMARY = Internal.createUniqueKey(OaMemberTb.OA_MEMBER_TB, "KEY_OA_MEMBER_TB_PRIMARY", OaMemberTb.OA_MEMBER_TB.ID);
        public static final UniqueKey<SbBoardFileinfoTbRecord> KEY_SB_BOARD_FILEINFO_TB_PRIMARY = Internal.createUniqueKey(SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB, "KEY_SB_BOARD_FILEINFO_TB_PRIMARY", SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB.ATTACH_ID);
        public static final UniqueKey<SbBoardFilelistTbRecord> KEY_SB_BOARD_FILELIST_TB_PRIMARY = Internal.createUniqueKey(SbBoardFilelistTb.SB_BOARD_FILELIST_TB, "KEY_SB_BOARD_FILELIST_TB_PRIMARY", SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_ID, SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_SQ);
        public static final UniqueKey<SbBoardInfoTbRecord> KEY_SB_BOARD_INFO_TB_PRIMARY = Internal.createUniqueKey(SbBoardInfoTb.SB_BOARD_INFO_TB, "KEY_SB_BOARD_INFO_TB_PRIMARY", SbBoardInfoTb.SB_BOARD_INFO_TB.BOARD_ID);
        public static final UniqueKey<SbBoardTbRecord> KEY_SB_BOARD_TB_PRIMARY = Internal.createUniqueKey(SbBoardTb.SB_BOARD_TB, "KEY_SB_BOARD_TB_PRIMARY", SbBoardTb.SB_BOARD_TB.BOARD_NO);
        public static final UniqueKey<SbBoardVoteTbRecord> KEY_SB_BOARD_VOTE_TB_PRIMARY = Internal.createUniqueKey(SbBoardVoteTb.SB_BOARD_VOTE_TB, "KEY_SB_BOARD_VOTE_TB_PRIMARY", SbBoardVoteTb.SB_BOARD_VOTE_TB.BOARD_NO, SbBoardVoteTb.SB_BOARD_VOTE_TB.USER_ID);
        public static final UniqueKey<SbGroupInfoTbRecord> KEY_SB_GROUP_INFO_TB_PRIMARY = Internal.createUniqueKey(SbGroupInfoTb.SB_GROUP_INFO_TB, "KEY_SB_GROUP_INFO_TB_PRIMARY", SbGroupInfoTb.SB_GROUP_INFO_TB.GROUP_ID);
        public static final UniqueKey<SbGroupTbRecord> KEY_SB_GROUP_TB_PRIMARY = Internal.createUniqueKey(SbGroupTb.SB_GROUP_TB, "KEY_SB_GROUP_TB_PRIMARY", SbGroupTb.SB_GROUP_TB.GROUP_ID, SbGroupTb.SB_GROUP_TB.USER_ID);
        public static final UniqueKey<SbMemberTbRecord> KEY_SB_MEMBER_TB_PRIMARY = Internal.createUniqueKey(SbMemberTb.SB_MEMBER_TB, "KEY_SB_MEMBER_TB_PRIMARY", SbMemberTb.SB_MEMBER_TB.USER_ID);
        public static final UniqueKey<SbMemberTbRecord> KEY_SB_MEMBER_TB_SB_MEMBER_IDX1 = Internal.createUniqueKey(SbMemberTb.SB_MEMBER_TB, "KEY_SB_MEMBER_TB_sb_member_idx1", SbMemberTb.SB_MEMBER_TB.NICKNAME);
        public static final UniqueKey<SbSeqTbRecord> KEY_SB_SEQ_TB_PRIMARY = Internal.createUniqueKey(SbSeqTb.SB_SEQ_TB, "KEY_SB_SEQ_TB_PRIMARY", SbSeqTb.SB_SEQ_TB.SQ_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<SbBoardFileinfoTbRecord, SbMemberTbRecord> SB_BOARD_FILEINFO_FK1 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_MEMBER_TB_PRIMARY, SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB, "sb_board_fileinfo_fk1", SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB.OWNER_ID);
        public static final ForeignKey<SbBoardFilelistTbRecord, SbBoardFileinfoTbRecord> SB_BOARD_FILELIST_FK1 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_BOARD_FILEINFO_TB_PRIMARY, SbBoardFilelistTb.SB_BOARD_FILELIST_TB, "sb_board_filelist_fk1", SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_ID);
        public static final ForeignKey<SbBoardTbRecord, SbBoardInfoTbRecord> SB_BOARD_FK1 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_BOARD_INFO_TB_PRIMARY, SbBoardTb.SB_BOARD_TB, "sb_board_fk1", SbBoardTb.SB_BOARD_TB.BOARD_ID);
        public static final ForeignKey<SbBoardTbRecord, SbMemberTbRecord> SB_BOARD_FK2 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_MEMBER_TB_PRIMARY, SbBoardTb.SB_BOARD_TB, "sb_board_fk2", SbBoardTb.SB_BOARD_TB.WRITER_ID);
        public static final ForeignKey<SbBoardTbRecord, SbBoardFileinfoTbRecord> SB_BOARD_FK3 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_BOARD_FILEINFO_TB_PRIMARY, SbBoardTb.SB_BOARD_TB, "sb_board_fk3", SbBoardTb.SB_BOARD_TB.ATTACH_ID);
        public static final ForeignKey<SbBoardVoteTbRecord, SbBoardTbRecord> SB_BOARD_VOTE_FK1 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_BOARD_TB_PRIMARY, SbBoardVoteTb.SB_BOARD_VOTE_TB, "sb_board_vote_fk1", SbBoardVoteTb.SB_BOARD_VOTE_TB.BOARD_NO);
        public static final ForeignKey<SbBoardVoteTbRecord, SbMemberTbRecord> SB_BOARD_VOTE_FK2 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_MEMBER_TB_PRIMARY, SbBoardVoteTb.SB_BOARD_VOTE_TB, "sb_board_vote_fk2", SbBoardVoteTb.SB_BOARD_VOTE_TB.USER_ID);
        public static final ForeignKey<SbGroupTbRecord, SbGroupInfoTbRecord> SB_GROUP_FK1 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_GROUP_INFO_TB_PRIMARY, SbGroupTb.SB_GROUP_TB, "sb_group_fk1", SbGroupTb.SB_GROUP_TB.GROUP_ID);
        public static final ForeignKey<SbGroupTbRecord, SbMemberTbRecord> SB_GROUP_FK2 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_MEMBER_TB_PRIMARY, SbGroupTb.SB_GROUP_TB, "sb_group_fk2", SbGroupTb.SB_GROUP_TB.USER_ID);
    }
}
