/*
 * This file is generated by jOOQ.
*/
package kr.pe.sinnori.impl.jooq;


import javax.annotation.Generated;

import kr.pe.sinnori.impl.jooq.tables.OaMemberTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardFileinfoTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardFilelistTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardInfoTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardVoteTb;
import kr.pe.sinnori.impl.jooq.tables.SbGroupInfoTb;
import kr.pe.sinnori.impl.jooq.tables.SbGroupTb;
import kr.pe.sinnori.impl.jooq.tables.SbMemberTb;
import kr.pe.sinnori.impl.jooq.tables.SbSeqTb;


/**
 * Convenience access to all tables in SB_DB
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>SB_DB.OA_MEMBER_TB</code>.
     */
    public static final OaMemberTb OA_MEMBER_TB = kr.pe.sinnori.impl.jooq.tables.OaMemberTb.OA_MEMBER_TB;

    /**
     * The table <code>SB_DB.SB_BOARD_FILEINFO_TB</code>.
     */
    public static final SbBoardFileinfoTb SB_BOARD_FILEINFO_TB = kr.pe.sinnori.impl.jooq.tables.SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB;

    /**
     * The table <code>SB_DB.SB_BOARD_FILELIST_TB</code>.
     */
    public static final SbBoardFilelistTb SB_BOARD_FILELIST_TB = kr.pe.sinnori.impl.jooq.tables.SbBoardFilelistTb.SB_BOARD_FILELIST_TB;

    /**
     * The table <code>SB_DB.SB_BOARD_INFO_TB</code>.
     */
    public static final SbBoardInfoTb SB_BOARD_INFO_TB = kr.pe.sinnori.impl.jooq.tables.SbBoardInfoTb.SB_BOARD_INFO_TB;

    /**
     * The table <code>SB_DB.SB_BOARD_TB</code>.
     */
    public static final SbBoardTb SB_BOARD_TB = kr.pe.sinnori.impl.jooq.tables.SbBoardTb.SB_BOARD_TB;

    /**
     * The table <code>SB_DB.SB_BOARD_VOTE_TB</code>.
     */
    public static final SbBoardVoteTb SB_BOARD_VOTE_TB = kr.pe.sinnori.impl.jooq.tables.SbBoardVoteTb.SB_BOARD_VOTE_TB;

    /**
     * The table <code>SB_DB.SB_GROUP_INFO_TB</code>.
     */
    public static final SbGroupInfoTb SB_GROUP_INFO_TB = kr.pe.sinnori.impl.jooq.tables.SbGroupInfoTb.SB_GROUP_INFO_TB;

    /**
     * The table <code>SB_DB.SB_GROUP_TB</code>.
     */
    public static final SbGroupTb SB_GROUP_TB = kr.pe.sinnori.impl.jooq.tables.SbGroupTb.SB_GROUP_TB;

    /**
     * The table <code>SB_DB.SB_MEMBER_TB</code>.
     */
    public static final SbMemberTb SB_MEMBER_TB = kr.pe.sinnori.impl.jooq.tables.SbMemberTb.SB_MEMBER_TB;

    /**
     * The table <code>SB_DB.SB_SEQ_TB</code>.
     */
    public static final SbSeqTb SB_SEQ_TB = kr.pe.sinnori.impl.jooq.tables.SbSeqTb.SB_SEQ_TB;
}
