/*
 * This file is generated by jOOQ.
*/
package kr.pe.sinnori.impl.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import kr.pe.sinnori.impl.jooq.Indexes;
import kr.pe.sinnori.impl.jooq.Keys;
import kr.pe.sinnori.impl.jooq.SbDb;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardFilelistTbRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbBoardFilelistTb extends TableImpl<SbBoardFilelistTbRecord> {

    private static final long serialVersionUID = 562561609;

    /**
     * The reference instance of <code>SB_DB.SB_BOARD_FILELIST_TB</code>
     */
    public static final SbBoardFilelistTb SB_BOARD_FILELIST_TB = new SbBoardFilelistTb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SbBoardFilelistTbRecord> getRecordType() {
        return SbBoardFilelistTbRecord.class;
    }

    /**
     * The column <code>SB_DB.SB_BOARD_FILELIST_TB.attach_id</code>. 업로드 식별자
     */
    public final TableField<SbBoardFilelistTbRecord, UInteger> ATTACH_ID = createField("attach_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "업로드 식별자");

    /**
     * The column <code>SB_DB.SB_BOARD_FILELIST_TB.attach_sq</code>. 첨부 파일 순번, 자동 증가
     */
    public final TableField<SbBoardFilelistTbRecord, UByte> ATTACH_SQ = createField("attach_sq", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "첨부 파일 순번, 자동 증가");

    /**
     * The column <code>SB_DB.SB_BOARD_FILELIST_TB.attach_fname</code>. 첨부 파일 이름
     */
    public final TableField<SbBoardFilelistTbRecord, String> ATTACH_FNAME = createField("attach_fname", org.jooq.impl.SQLDataType.VARCHAR(255), this, "첨부 파일 이름");

    /**
     * The column <code>SB_DB.SB_BOARD_FILELIST_TB.sys_fname</code>. 첨부 파일의 시스템 절대 경로 파일명
     */
    public final TableField<SbBoardFilelistTbRecord, String> SYS_FNAME = createField("sys_fname", org.jooq.impl.SQLDataType.VARCHAR(600), this, "첨부 파일의 시스템 절대 경로 파일명");

    /**
     * Create a <code>SB_DB.SB_BOARD_FILELIST_TB</code> table reference
     */
    public SbBoardFilelistTb() {
        this(DSL.name("SB_BOARD_FILELIST_TB"), null);
    }

    /**
     * Create an aliased <code>SB_DB.SB_BOARD_FILELIST_TB</code> table reference
     */
    public SbBoardFilelistTb(String alias) {
        this(DSL.name(alias), SB_BOARD_FILELIST_TB);
    }

    /**
     * Create an aliased <code>SB_DB.SB_BOARD_FILELIST_TB</code> table reference
     */
    public SbBoardFilelistTb(Name alias) {
        this(alias, SB_BOARD_FILELIST_TB);
    }

    private SbBoardFilelistTb(Name alias, Table<SbBoardFilelistTbRecord> aliased) {
        this(alias, aliased, null);
    }

    private SbBoardFilelistTb(Name alias, Table<SbBoardFilelistTbRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SbDb.SB_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SB_BOARD_FILELIST_TB_FK_TW_BOARD_FILELIST_01_IDX, Indexes.SB_BOARD_FILELIST_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SbBoardFilelistTbRecord> getPrimaryKey() {
        return Keys.KEY_SB_BOARD_FILELIST_TB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SbBoardFilelistTbRecord>> getKeys() {
        return Arrays.<UniqueKey<SbBoardFilelistTbRecord>>asList(Keys.KEY_SB_BOARD_FILELIST_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SbBoardFilelistTbRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SbBoardFilelistTbRecord, ?>>asList(Keys.FK_SB_BOARD_FILELIST_01);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTb as(String alias) {
        return new SbBoardFilelistTb(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTb as(Name alias) {
        return new SbBoardFilelistTb(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SbBoardFilelistTb rename(String name) {
        return new SbBoardFilelistTb(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SbBoardFilelistTb rename(Name name) {
        return new SbBoardFilelistTb(name, null);
    }
}
