/*
 * This file is generated by jOOQ.
*/
package kr.pe.sinnori.impl.jooq;


import javax.annotation.Generated;

import kr.pe.sinnori.impl.jooq.tables.OaMemberTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardFileinfoTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardFilelistTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardInfoTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardTb;
import kr.pe.sinnori.impl.jooq.tables.SbBoardVoteTb;
import kr.pe.sinnori.impl.jooq.tables.SbGroupInfoTb;
import kr.pe.sinnori.impl.jooq.tables.SbGroupTb;
import kr.pe.sinnori.impl.jooq.tables.SbMemberTb;
import kr.pe.sinnori.impl.jooq.tables.SbSeqManagerTb;
import kr.pe.sinnori.impl.jooq.tables.records.OaMemberTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardFileinfoTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardFilelistTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardInfoTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbBoardVoteTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbGroupInfoTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbGroupTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbMemberTbRecord;
import kr.pe.sinnori.impl.jooq.tables.records.SbSeqManagerTbRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>SB_DB</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<SbBoardFileinfoTbRecord, UInteger> IDENTITY_SB_BOARD_FILEINFO_TB = Identities0.IDENTITY_SB_BOARD_FILEINFO_TB;
    public static final Identity<SbBoardTbRecord, UInteger> IDENTITY_SB_BOARD_TB = Identities0.IDENTITY_SB_BOARD_TB;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OaMemberTbRecord> KEY_OA_MEMBER_TB_PRIMARY = UniqueKeys0.KEY_OA_MEMBER_TB_PRIMARY;
    public static final UniqueKey<SbBoardFileinfoTbRecord> KEY_SB_BOARD_FILEINFO_TB_PRIMARY = UniqueKeys0.KEY_SB_BOARD_FILEINFO_TB_PRIMARY;
    public static final UniqueKey<SbBoardFilelistTbRecord> KEY_SB_BOARD_FILELIST_TB_PRIMARY = UniqueKeys0.KEY_SB_BOARD_FILELIST_TB_PRIMARY;
    public static final UniqueKey<SbBoardInfoTbRecord> KEY_SB_BOARD_INFO_TB_PRIMARY = UniqueKeys0.KEY_SB_BOARD_INFO_TB_PRIMARY;
    public static final UniqueKey<SbBoardTbRecord> KEY_SB_BOARD_TB_PRIMARY = UniqueKeys0.KEY_SB_BOARD_TB_PRIMARY;
    public static final UniqueKey<SbBoardVoteTbRecord> KEY_SB_BOARD_VOTE_TB_PRIMARY = UniqueKeys0.KEY_SB_BOARD_VOTE_TB_PRIMARY;
    public static final UniqueKey<SbGroupInfoTbRecord> KEY_SB_GROUP_INFO_TB_PRIMARY = UniqueKeys0.KEY_SB_GROUP_INFO_TB_PRIMARY;
    public static final UniqueKey<SbGroupTbRecord> KEY_SB_GROUP_TB_PRIMARY = UniqueKeys0.KEY_SB_GROUP_TB_PRIMARY;
    public static final UniqueKey<SbMemberTbRecord> KEY_SB_MEMBER_TB_PRIMARY = UniqueKeys0.KEY_SB_MEMBER_TB_PRIMARY;
    public static final UniqueKey<SbMemberTbRecord> KEY_SB_MEMBER_TB_TW_MEMBER_01_IDX = UniqueKeys0.KEY_SB_MEMBER_TB_TW_MEMBER_01_IDX;
    public static final UniqueKey<SbSeqManagerTbRecord> KEY_SB_SEQ_MANAGER_TB_PRIMARY = UniqueKeys0.KEY_SB_SEQ_MANAGER_TB_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SbBoardFileinfoTbRecord, SbMemberTbRecord> FK_SB_BOARD_FILEINFO_01 = ForeignKeys0.FK_SB_BOARD_FILEINFO_01;
    public static final ForeignKey<SbBoardFilelistTbRecord, SbBoardFileinfoTbRecord> FK_SB_BOARD_FILELIST_01 = ForeignKeys0.FK_SB_BOARD_FILELIST_01;
    public static final ForeignKey<SbBoardTbRecord, SbBoardInfoTbRecord> FK_SB_BOARD_02 = ForeignKeys0.FK_SB_BOARD_02;
    public static final ForeignKey<SbBoardTbRecord, SbMemberTbRecord> FK_SB_BOARD_01 = ForeignKeys0.FK_SB_BOARD_01;
    public static final ForeignKey<SbBoardTbRecord, SbBoardFileinfoTbRecord> FK_SB_BOARD_03 = ForeignKeys0.FK_SB_BOARD_03;
    public static final ForeignKey<SbBoardVoteTbRecord, SbBoardTbRecord> FK_SB_BOARD_VOTE_01 = ForeignKeys0.FK_SB_BOARD_VOTE_01;
    public static final ForeignKey<SbBoardVoteTbRecord, SbMemberTbRecord> FK_SB_BOARD_VOTE_02 = ForeignKeys0.FK_SB_BOARD_VOTE_02;
    public static final ForeignKey<SbGroupTbRecord, SbGroupInfoTbRecord> FK_SB_GROUP_01 = ForeignKeys0.FK_SB_GROUP_01;
    public static final ForeignKey<SbGroupTbRecord, SbMemberTbRecord> FK_SB_GROUP_02 = ForeignKeys0.FK_SB_GROUP_02;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<SbBoardFileinfoTbRecord, UInteger> IDENTITY_SB_BOARD_FILEINFO_TB = Internal.createIdentity(SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB, SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB.ATTACH_ID);
        public static Identity<SbBoardTbRecord, UInteger> IDENTITY_SB_BOARD_TB = Internal.createIdentity(SbBoardTb.SB_BOARD_TB, SbBoardTb.SB_BOARD_TB.BOARD_NO);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<OaMemberTbRecord> KEY_OA_MEMBER_TB_PRIMARY = Internal.createUniqueKey(OaMemberTb.OA_MEMBER_TB, "KEY_OA_MEMBER_TB_PRIMARY", OaMemberTb.OA_MEMBER_TB.ID);
        public static final UniqueKey<SbBoardFileinfoTbRecord> KEY_SB_BOARD_FILEINFO_TB_PRIMARY = Internal.createUniqueKey(SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB, "KEY_SB_BOARD_FILEINFO_TB_PRIMARY", SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB.ATTACH_ID);
        public static final UniqueKey<SbBoardFilelistTbRecord> KEY_SB_BOARD_FILELIST_TB_PRIMARY = Internal.createUniqueKey(SbBoardFilelistTb.SB_BOARD_FILELIST_TB, "KEY_SB_BOARD_FILELIST_TB_PRIMARY", SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_SQ, SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_ID);
        public static final UniqueKey<SbBoardInfoTbRecord> KEY_SB_BOARD_INFO_TB_PRIMARY = Internal.createUniqueKey(SbBoardInfoTb.SB_BOARD_INFO_TB, "KEY_SB_BOARD_INFO_TB_PRIMARY", SbBoardInfoTb.SB_BOARD_INFO_TB.BOARD_ID);
        public static final UniqueKey<SbBoardTbRecord> KEY_SB_BOARD_TB_PRIMARY = Internal.createUniqueKey(SbBoardTb.SB_BOARD_TB, "KEY_SB_BOARD_TB_PRIMARY", SbBoardTb.SB_BOARD_TB.BOARD_NO);
        public static final UniqueKey<SbBoardVoteTbRecord> KEY_SB_BOARD_VOTE_TB_PRIMARY = Internal.createUniqueKey(SbBoardVoteTb.SB_BOARD_VOTE_TB, "KEY_SB_BOARD_VOTE_TB_PRIMARY", SbBoardVoteTb.SB_BOARD_VOTE_TB.BOARD_NO, SbBoardVoteTb.SB_BOARD_VOTE_TB.USER_ID);
        public static final UniqueKey<SbGroupInfoTbRecord> KEY_SB_GROUP_INFO_TB_PRIMARY = Internal.createUniqueKey(SbGroupInfoTb.SB_GROUP_INFO_TB, "KEY_SB_GROUP_INFO_TB_PRIMARY", SbGroupInfoTb.SB_GROUP_INFO_TB.GROUP_ID);
        public static final UniqueKey<SbGroupTbRecord> KEY_SB_GROUP_TB_PRIMARY = Internal.createUniqueKey(SbGroupTb.SB_GROUP_TB, "KEY_SB_GROUP_TB_PRIMARY", SbGroupTb.SB_GROUP_TB.GROUP_ID, SbGroupTb.SB_GROUP_TB.USER_ID);
        public static final UniqueKey<SbMemberTbRecord> KEY_SB_MEMBER_TB_PRIMARY = Internal.createUniqueKey(SbMemberTb.SB_MEMBER_TB, "KEY_SB_MEMBER_TB_PRIMARY", SbMemberTb.SB_MEMBER_TB.USER_ID);
        public static final UniqueKey<SbMemberTbRecord> KEY_SB_MEMBER_TB_TW_MEMBER_01_IDX = Internal.createUniqueKey(SbMemberTb.SB_MEMBER_TB, "KEY_SB_MEMBER_TB_tw_member_01_idx", SbMemberTb.SB_MEMBER_TB.NICKNAME);
        public static final UniqueKey<SbSeqManagerTbRecord> KEY_SB_SEQ_MANAGER_TB_PRIMARY = Internal.createUniqueKey(SbSeqManagerTb.SB_SEQ_MANAGER_TB, "KEY_SB_SEQ_MANAGER_TB_PRIMARY", SbSeqManagerTb.SB_SEQ_MANAGER_TB.SQ_TYPE_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<SbBoardFileinfoTbRecord, SbMemberTbRecord> FK_SB_BOARD_FILEINFO_01 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_MEMBER_TB_PRIMARY, SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB, "fk_sb_board_fileinfo_01", SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB.OWNER_ID);
        public static final ForeignKey<SbBoardFilelistTbRecord, SbBoardFileinfoTbRecord> FK_SB_BOARD_FILELIST_01 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_BOARD_FILEINFO_TB_PRIMARY, SbBoardFilelistTb.SB_BOARD_FILELIST_TB, "fk_sb_board_filelist_01", SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_ID);
        public static final ForeignKey<SbBoardTbRecord, SbBoardInfoTbRecord> FK_SB_BOARD_02 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_BOARD_INFO_TB_PRIMARY, SbBoardTb.SB_BOARD_TB, "fk_sb_board_02", SbBoardTb.SB_BOARD_TB.BOARD_ID);
        public static final ForeignKey<SbBoardTbRecord, SbMemberTbRecord> FK_SB_BOARD_01 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_MEMBER_TB_PRIMARY, SbBoardTb.SB_BOARD_TB, "fk_sb_board_01", SbBoardTb.SB_BOARD_TB.WRITER_ID);
        public static final ForeignKey<SbBoardTbRecord, SbBoardFileinfoTbRecord> FK_SB_BOARD_03 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_BOARD_FILEINFO_TB_PRIMARY, SbBoardTb.SB_BOARD_TB, "fk_sb_board_03", SbBoardTb.SB_BOARD_TB.ATTACH_ID);
        public static final ForeignKey<SbBoardVoteTbRecord, SbBoardTbRecord> FK_SB_BOARD_VOTE_01 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_BOARD_TB_PRIMARY, SbBoardVoteTb.SB_BOARD_VOTE_TB, "fk_sb_board_vote_01", SbBoardVoteTb.SB_BOARD_VOTE_TB.BOARD_NO);
        public static final ForeignKey<SbBoardVoteTbRecord, SbMemberTbRecord> FK_SB_BOARD_VOTE_02 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_MEMBER_TB_PRIMARY, SbBoardVoteTb.SB_BOARD_VOTE_TB, "fk_sb_board_vote_02", SbBoardVoteTb.SB_BOARD_VOTE_TB.USER_ID);
        public static final ForeignKey<SbGroupTbRecord, SbGroupInfoTbRecord> FK_SB_GROUP_01 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_GROUP_INFO_TB_PRIMARY, SbGroupTb.SB_GROUP_TB, "fk_sb_group_01", SbGroupTb.SB_GROUP_TB.GROUP_ID);
        public static final ForeignKey<SbGroupTbRecord, SbMemberTbRecord> FK_SB_GROUP_02 = Internal.createForeignKey(kr.pe.sinnori.impl.jooq.Keys.KEY_SB_MEMBER_TB_PRIMARY, SbGroupTb.SB_GROUP_TB, "fk_sb_group_02", SbGroupTb.SB_GROUP_TB.USER_ID);
    }
}
