/*
 * This file is generated by jOOQ.
*/
package kr.pe.sinnori.impl.jooq.tables.records;


import javax.annotation.Generated;

import kr.pe.sinnori.impl.jooq.tables.SbSeqManagerTb;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbSeqManagerTbRecord extends UpdatableRecordImpl<SbSeqManagerTbRecord> implements Record3<UByte, UInteger, String> {

    private static final long serialVersionUID = 319439206;

    /**
     * Setter for <code>SB_DB.SB_SEQ_MANAGER_TB.sq_type_id</code>. 시퀀스 종류 식별자, 1:업로드 파일 이름 시퀀스
     */
    public void setSqTypeId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>SB_DB.SB_SEQ_MANAGER_TB.sq_type_id</code>. 시퀀스 종류 식별자, 1:업로드 파일 이름 시퀀스
     */
    public UByte getSqTypeId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>SB_DB.SB_SEQ_MANAGER_TB.sq_value</code>.
     */
    public void setSqValue(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>SB_DB.SB_SEQ_MANAGER_TB.sq_value</code>.
     */
    public UInteger getSqValue() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>SB_DB.SB_SEQ_MANAGER_TB.sq_type_name</code>.
     */
    public void setSqTypeName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SB_DB.SB_SEQ_MANAGER_TB.sq_type_name</code>.
     */
    public String getSqTypeName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UByte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UByte, UInteger, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UByte, UInteger, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return SbSeqManagerTb.SB_SEQ_MANAGER_TB.SQ_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbSeqManagerTb.SB_SEQ_MANAGER_TB.SQ_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SbSeqManagerTb.SB_SEQ_MANAGER_TB.SQ_TYPE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getSqTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getSqValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSqTypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getSqTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getSqValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSqTypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSeqManagerTbRecord value1(UByte value) {
        setSqTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSeqManagerTbRecord value2(UInteger value) {
        setSqValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSeqManagerTbRecord value3(String value) {
        setSqTypeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSeqManagerTbRecord values(UByte value1, UInteger value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbSeqManagerTbRecord
     */
    public SbSeqManagerTbRecord() {
        super(SbSeqManagerTb.SB_SEQ_MANAGER_TB);
    }

    /**
     * Create a detached, initialised SbSeqManagerTbRecord
     */
    public SbSeqManagerTbRecord(UByte sqTypeId, UInteger sqValue, String sqTypeName) {
        super(SbSeqManagerTb.SB_SEQ_MANAGER_TB);

        set(0, sqTypeId);
        set(1, sqValue);
        set(2, sqTypeName);
    }
}
