/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq;


import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.OaMemberTb;
import kr.pe.codda.impl.jooq.tables.SbBoardFileinfoTb;
import kr.pe.codda.impl.jooq.tables.SbBoardFilelistTb;
import kr.pe.codda.impl.jooq.tables.SbBoardInfoTb;
import kr.pe.codda.impl.jooq.tables.SbBoardTb;
import kr.pe.codda.impl.jooq.tables.SbBoardVoteTb;
import kr.pe.codda.impl.jooq.tables.SbGroupInfoTb;
import kr.pe.codda.impl.jooq.tables.SbGroupTb;
import kr.pe.codda.impl.jooq.tables.SbMemberTb;
import kr.pe.codda.impl.jooq.tables.SbSeqTb;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>SB_DB</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index OA_MEMBER_TB_PRIMARY = Indexes0.OA_MEMBER_TB_PRIMARY;
    public static final Index SB_BOARD_FILEINFO_TB_PRIMARY = Indexes0.SB_BOARD_FILEINFO_TB_PRIMARY;
    public static final Index SB_BOARD_FILEINFO_TB_SB_BOARD_FILEINFO_FK1_IDX = Indexes0.SB_BOARD_FILEINFO_TB_SB_BOARD_FILEINFO_FK1_IDX;
    public static final Index SB_BOARD_FILELIST_TB_PRIMARY = Indexes0.SB_BOARD_FILELIST_TB_PRIMARY;
    public static final Index SB_BOARD_INFO_TB_PRIMARY = Indexes0.SB_BOARD_INFO_TB_PRIMARY;
    public static final Index SB_BOARD_TB_PRIMARY = Indexes0.SB_BOARD_TB_PRIMARY;
    public static final Index SB_BOARD_TB_SB_BOARD_FK1_IDX = Indexes0.SB_BOARD_TB_SB_BOARD_FK1_IDX;
    public static final Index SB_BOARD_TB_SB_BOARD_FK2_IDX = Indexes0.SB_BOARD_TB_SB_BOARD_FK2_IDX;
    public static final Index SB_BOARD_TB_SB_BOARD_FK3_IDX = Indexes0.SB_BOARD_TB_SB_BOARD_FK3_IDX;
    public static final Index SB_BOARD_TB_SB_BOARD_IDX1 = Indexes0.SB_BOARD_TB_SB_BOARD_IDX1;
    public static final Index SB_BOARD_VOTE_TB_PRIMARY = Indexes0.SB_BOARD_VOTE_TB_PRIMARY;
    public static final Index SB_BOARD_VOTE_TB_SB_BOARD_VOTE_FK2_IDX = Indexes0.SB_BOARD_VOTE_TB_SB_BOARD_VOTE_FK2_IDX;
    public static final Index SB_GROUP_INFO_TB_PRIMARY = Indexes0.SB_GROUP_INFO_TB_PRIMARY;
    public static final Index SB_GROUP_TB_PRIMARY = Indexes0.SB_GROUP_TB_PRIMARY;
    public static final Index SB_GROUP_TB_SB_GROUP_FK2_IDX = Indexes0.SB_GROUP_TB_SB_GROUP_FK2_IDX;
    public static final Index SB_MEMBER_TB_PRIMARY = Indexes0.SB_MEMBER_TB_PRIMARY;
    public static final Index SB_MEMBER_TB_SB_MEMBER_IDX1 = Indexes0.SB_MEMBER_TB_SB_MEMBER_IDX1;
    public static final Index SB_MEMBER_TB_SB_MEMBER_IDX2 = Indexes0.SB_MEMBER_TB_SB_MEMBER_IDX2;
    public static final Index SB_SEQ_TB_PRIMARY = Indexes0.SB_SEQ_TB_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index OA_MEMBER_TB_PRIMARY = Internal.createIndex("PRIMARY", OaMemberTb.OA_MEMBER_TB, new OrderField[] { OaMemberTb.OA_MEMBER_TB.ID }, true);
        public static Index SB_BOARD_FILEINFO_TB_PRIMARY = Internal.createIndex("PRIMARY", SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB, new OrderField[] { SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB.ATTACH_ID }, true);
        public static Index SB_BOARD_FILEINFO_TB_SB_BOARD_FILEINFO_FK1_IDX = Internal.createIndex("sb_board_fileinfo_fk1_idx", SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB, new OrderField[] { SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB.OWNER_ID }, false);
        public static Index SB_BOARD_FILELIST_TB_PRIMARY = Internal.createIndex("PRIMARY", SbBoardFilelistTb.SB_BOARD_FILELIST_TB, new OrderField[] { SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_ID, SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_SQ }, true);
        public static Index SB_BOARD_INFO_TB_PRIMARY = Internal.createIndex("PRIMARY", SbBoardInfoTb.SB_BOARD_INFO_TB, new OrderField[] { SbBoardInfoTb.SB_BOARD_INFO_TB.BOARD_ID }, true);
        public static Index SB_BOARD_TB_PRIMARY = Internal.createIndex("PRIMARY", SbBoardTb.SB_BOARD_TB, new OrderField[] { SbBoardTb.SB_BOARD_TB.BOARD_NO }, true);
        public static Index SB_BOARD_TB_SB_BOARD_FK1_IDX = Internal.createIndex("sb_board_fk1_idx", SbBoardTb.SB_BOARD_TB, new OrderField[] { SbBoardTb.SB_BOARD_TB.BOARD_ID }, false);
        public static Index SB_BOARD_TB_SB_BOARD_FK2_IDX = Internal.createIndex("sb_board_fk2_idx", SbBoardTb.SB_BOARD_TB, new OrderField[] { SbBoardTb.SB_BOARD_TB.WRITER_ID }, false);
        public static Index SB_BOARD_TB_SB_BOARD_FK3_IDX = Internal.createIndex("sb_board_fk3_idx", SbBoardTb.SB_BOARD_TB, new OrderField[] { SbBoardTb.SB_BOARD_TB.ATTACH_ID }, false);
        public static Index SB_BOARD_TB_SB_BOARD_IDX1 = Internal.createIndex("sb_board_idx1", SbBoardTb.SB_BOARD_TB, new OrderField[] { SbBoardTb.SB_BOARD_TB.BOARD_ID, SbBoardTb.SB_BOARD_TB.GROUP_NO }, false);
        public static Index SB_BOARD_VOTE_TB_PRIMARY = Internal.createIndex("PRIMARY", SbBoardVoteTb.SB_BOARD_VOTE_TB, new OrderField[] { SbBoardVoteTb.SB_BOARD_VOTE_TB.BOARD_NO, SbBoardVoteTb.SB_BOARD_VOTE_TB.USER_ID }, true);
        public static Index SB_BOARD_VOTE_TB_SB_BOARD_VOTE_FK2_IDX = Internal.createIndex("sb_board_vote_fk2_idx", SbBoardVoteTb.SB_BOARD_VOTE_TB, new OrderField[] { SbBoardVoteTb.SB_BOARD_VOTE_TB.USER_ID }, false);
        public static Index SB_GROUP_INFO_TB_PRIMARY = Internal.createIndex("PRIMARY", SbGroupInfoTb.SB_GROUP_INFO_TB, new OrderField[] { SbGroupInfoTb.SB_GROUP_INFO_TB.GROUP_ID }, true);
        public static Index SB_GROUP_TB_PRIMARY = Internal.createIndex("PRIMARY", SbGroupTb.SB_GROUP_TB, new OrderField[] { SbGroupTb.SB_GROUP_TB.GROUP_ID, SbGroupTb.SB_GROUP_TB.USER_ID }, true);
        public static Index SB_GROUP_TB_SB_GROUP_FK2_IDX = Internal.createIndex("sb_group_fk2_idx", SbGroupTb.SB_GROUP_TB, new OrderField[] { SbGroupTb.SB_GROUP_TB.USER_ID }, false);
        public static Index SB_MEMBER_TB_PRIMARY = Internal.createIndex("PRIMARY", SbMemberTb.SB_MEMBER_TB, new OrderField[] { SbMemberTb.SB_MEMBER_TB.USER_ID }, true);
        public static Index SB_MEMBER_TB_SB_MEMBER_IDX1 = Internal.createIndex("sb_member_idx1", SbMemberTb.SB_MEMBER_TB, new OrderField[] { SbMemberTb.SB_MEMBER_TB.NICKNAME }, true);
        public static Index SB_MEMBER_TB_SB_MEMBER_IDX2 = Internal.createIndex("sb_member_idx2", SbMemberTb.SB_MEMBER_TB, new OrderField[] { SbMemberTb.SB_MEMBER_TB.MEMBER_ST }, false);
        public static Index SB_SEQ_TB_PRIMARY = Internal.createIndex("PRIMARY", SbSeqTb.SB_SEQ_TB, new OrderField[] { SbSeqTb.SB_SEQ_TB.SQ_ID }, true);
    }
}
