/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.OaMemberTb;
import kr.pe.codda.impl.jooq.tables.SbBoardFileinfoTb;
import kr.pe.codda.impl.jooq.tables.SbBoardFilelistTb;
import kr.pe.codda.impl.jooq.tables.SbBoardInfoTb;
import kr.pe.codda.impl.jooq.tables.SbBoardTb;
import kr.pe.codda.impl.jooq.tables.SbBoardVoteTb;
import kr.pe.codda.impl.jooq.tables.SbGroupInfoTb;
import kr.pe.codda.impl.jooq.tables.SbGroupTb;
import kr.pe.codda.impl.jooq.tables.SbMemberTb;
import kr.pe.codda.impl.jooq.tables.SbSeqTb;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbDb extends SchemaImpl {

    private static final long serialVersionUID = 1376161855;

    /**
     * The reference instance of <code>SB_DB</code>
     */
    public static final SbDb SB_DB = new SbDb();

    /**
     * The table <code>SB_DB.OA_MEMBER_TB</code>.
     */
    public final OaMemberTb OA_MEMBER_TB = kr.pe.codda.impl.jooq.tables.OaMemberTb.OA_MEMBER_TB;

    /**
     * The table <code>SB_DB.SB_BOARD_FILEINFO_TB</code>.
     */
    public final SbBoardFileinfoTb SB_BOARD_FILEINFO_TB = kr.pe.codda.impl.jooq.tables.SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB;

    /**
     * The table <code>SB_DB.SB_BOARD_FILELIST_TB</code>.
     */
    public final SbBoardFilelistTb SB_BOARD_FILELIST_TB = kr.pe.codda.impl.jooq.tables.SbBoardFilelistTb.SB_BOARD_FILELIST_TB;

    /**
     * The table <code>SB_DB.SB_BOARD_INFO_TB</code>.
     */
    public final SbBoardInfoTb SB_BOARD_INFO_TB = kr.pe.codda.impl.jooq.tables.SbBoardInfoTb.SB_BOARD_INFO_TB;

    /**
     * The table <code>SB_DB.SB_BOARD_TB</code>.
     */
    public final SbBoardTb SB_BOARD_TB = kr.pe.codda.impl.jooq.tables.SbBoardTb.SB_BOARD_TB;

    /**
     * The table <code>SB_DB.SB_BOARD_VOTE_TB</code>.
     */
    public final SbBoardVoteTb SB_BOARD_VOTE_TB = kr.pe.codda.impl.jooq.tables.SbBoardVoteTb.SB_BOARD_VOTE_TB;

    /**
     * The table <code>SB_DB.SB_GROUP_INFO_TB</code>.
     */
    public final SbGroupInfoTb SB_GROUP_INFO_TB = kr.pe.codda.impl.jooq.tables.SbGroupInfoTb.SB_GROUP_INFO_TB;

    /**
     * The table <code>SB_DB.SB_GROUP_TB</code>.
     */
    public final SbGroupTb SB_GROUP_TB = kr.pe.codda.impl.jooq.tables.SbGroupTb.SB_GROUP_TB;

    /**
     * The table <code>SB_DB.SB_MEMBER_TB</code>.
     */
    public final SbMemberTb SB_MEMBER_TB = kr.pe.codda.impl.jooq.tables.SbMemberTb.SB_MEMBER_TB;

    /**
     * The table <code>SB_DB.SB_SEQ_TB</code>.
     */
    public final SbSeqTb SB_SEQ_TB = kr.pe.codda.impl.jooq.tables.SbSeqTb.SB_SEQ_TB;

    /**
     * No further instances allowed
     */
    private SbDb() {
        super("SB_DB", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            OaMemberTb.OA_MEMBER_TB,
            SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB,
            SbBoardFilelistTb.SB_BOARD_FILELIST_TB,
            SbBoardInfoTb.SB_BOARD_INFO_TB,
            SbBoardTb.SB_BOARD_TB,
            SbBoardVoteTb.SB_BOARD_VOTE_TB,
            SbGroupInfoTb.SB_GROUP_INFO_TB,
            SbGroupTb.SB_GROUP_TB,
            SbMemberTb.SB_MEMBER_TB,
            SbSeqTb.SB_SEQ_TB);
    }
}
