/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq;


import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.OaMemberTb;
import kr.pe.codda.impl.jooq.tables.SbBoardFileinfoTb;
import kr.pe.codda.impl.jooq.tables.SbBoardFilelistTb;
import kr.pe.codda.impl.jooq.tables.SbBoardInfoTb;
import kr.pe.codda.impl.jooq.tables.SbBoardTb;
import kr.pe.codda.impl.jooq.tables.SbBoardVoteTb;
import kr.pe.codda.impl.jooq.tables.SbGroupInfoTb;
import kr.pe.codda.impl.jooq.tables.SbGroupTb;
import kr.pe.codda.impl.jooq.tables.SbMemberTb;
import kr.pe.codda.impl.jooq.tables.SbSeqTb;
import kr.pe.codda.impl.jooq.tables.SbSitemenuTb;


/**
 * Convenience access to all tables in sb_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sb_db.oa_member_tb</code>.
     */
    public static final OaMemberTb OA_MEMBER_TB = kr.pe.codda.impl.jooq.tables.OaMemberTb.OA_MEMBER_TB;

    /**
     * The table <code>sb_db.sb_board_fileinfo_tb</code>.
     */
    public static final SbBoardFileinfoTb SB_BOARD_FILEINFO_TB = kr.pe.codda.impl.jooq.tables.SbBoardFileinfoTb.SB_BOARD_FILEINFO_TB;

    /**
     * The table <code>sb_db.sb_board_filelist_tb</code>.
     */
    public static final SbBoardFilelistTb SB_BOARD_FILELIST_TB = kr.pe.codda.impl.jooq.tables.SbBoardFilelistTb.SB_BOARD_FILELIST_TB;

    /**
     * The table <code>sb_db.sb_board_info_tb</code>.
     */
    public static final SbBoardInfoTb SB_BOARD_INFO_TB = kr.pe.codda.impl.jooq.tables.SbBoardInfoTb.SB_BOARD_INFO_TB;

    /**
     * The table <code>sb_db.sb_board_tb</code>.
     */
    public static final SbBoardTb SB_BOARD_TB = kr.pe.codda.impl.jooq.tables.SbBoardTb.SB_BOARD_TB;

    /**
     * The table <code>sb_db.sb_board_vote_tb</code>.
     */
    public static final SbBoardVoteTb SB_BOARD_VOTE_TB = kr.pe.codda.impl.jooq.tables.SbBoardVoteTb.SB_BOARD_VOTE_TB;

    /**
     * The table <code>sb_db.sb_group_info_tb</code>.
     */
    public static final SbGroupInfoTb SB_GROUP_INFO_TB = kr.pe.codda.impl.jooq.tables.SbGroupInfoTb.SB_GROUP_INFO_TB;

    /**
     * The table <code>sb_db.sb_group_tb</code>.
     */
    public static final SbGroupTb SB_GROUP_TB = kr.pe.codda.impl.jooq.tables.SbGroupTb.SB_GROUP_TB;

    /**
     * The table <code>sb_db.sb_member_tb</code>.
     */
    public static final SbMemberTb SB_MEMBER_TB = kr.pe.codda.impl.jooq.tables.SbMemberTb.SB_MEMBER_TB;

    /**
     * The table <code>sb_db.sb_seq_tb</code>.
     */
    public static final SbSeqTb SB_SEQ_TB = kr.pe.codda.impl.jooq.tables.SbSeqTb.SB_SEQ_TB;

    /**
     * The table <code>sb_db.sb_sitemenu_tb</code>.
     */
    public static final SbSitemenuTb SB_SITEMENU_TB = kr.pe.codda.impl.jooq.tables.SbSitemenuTb.SB_SITEMENU_TB;
}
