/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables.records;


import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.SbBoardFilelistTb;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbBoardFilelistTbRecord extends UpdatableRecordImpl<SbBoardFilelistTbRecord> implements Record4<UByte, UInteger, UByte, String> {

    private static final long serialVersionUID = -1668313553;

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.board_id</code>.
     */
    public void setBoardId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.board_id</code>.
     */
    public UByte getBoardId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.board_no</code>.
     */
    public void setBoardNo(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.board_no</code>.
     */
    public UInteger getBoardNo() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.attached_file_sq</code>. 첨부 파일 순번
     */
    public void setAttachedFileSq(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.attached_file_sq</code>. 첨부 파일 순번
     */
    public UByte getAttachedFileSq() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.attached_fname</code>. 첨부 파일 이름
     */
    public void setAttachedFname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.attached_fname</code>. 첨부 파일 이름
     */
    public String getAttachedFname() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<UByte, UInteger, UByte> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UByte, UInteger, UByte, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UByte, UInteger, UByte, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.BOARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.BOARD_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACHED_FILE_SQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACHED_FNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getBoardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getBoardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getAttachedFileSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAttachedFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getBoardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getBoardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getAttachedFileSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAttachedFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value1(UByte value) {
        setBoardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value2(UInteger value) {
        setBoardNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value3(UByte value) {
        setAttachedFileSq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value4(String value) {
        setAttachedFname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord values(UByte value1, UInteger value2, UByte value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbBoardFilelistTbRecord
     */
    public SbBoardFilelistTbRecord() {
        super(SbBoardFilelistTb.SB_BOARD_FILELIST_TB);
    }

    /**
     * Create a detached, initialised SbBoardFilelistTbRecord
     */
    public SbBoardFilelistTbRecord(UByte boardId, UInteger boardNo, UByte attachedFileSq, String attachedFname) {
        super(SbBoardFilelistTb.SB_BOARD_FILELIST_TB);

        set(0, boardId);
        set(1, boardNo);
        set(2, attachedFileSq);
        set(3, attachedFname);
    }
}
