/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables.records;


import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.SbBoardFilelistTb;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbBoardFilelistTbRecord extends UpdatableRecordImpl<SbBoardFilelistTbRecord> implements Record4<UInteger, UInteger, String, String> {

    private static final long serialVersionUID = 534026371;

    /**
     * Setter for <code>SB_DB.SB_BOARD_FILELIST_TB.attach_id</code>. 업로드 식별자
     */
    public void setAttachId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>SB_DB.SB_BOARD_FILELIST_TB.attach_id</code>. 업로드 식별자
     */
    public UInteger getAttachId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>SB_DB.SB_BOARD_FILELIST_TB.attach_sq</code>. 첨부 파일 순번, 자동 증가
     */
    public void setAttachSq(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>SB_DB.SB_BOARD_FILELIST_TB.attach_sq</code>. 첨부 파일 순번, 자동 증가
     */
    public UInteger getAttachSq() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>SB_DB.SB_BOARD_FILELIST_TB.attach_fname</code>. 첨부 파일 이름
     */
    public void setAttachFname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SB_DB.SB_BOARD_FILELIST_TB.attach_fname</code>. 첨부 파일 이름
     */
    public String getAttachFname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SB_DB.SB_BOARD_FILELIST_TB.sys_fname</code>. 첨부 파일의 시스템 절대 경로 파일명
     */
    public void setSysFname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SB_DB.SB_BOARD_FILELIST_TB.sys_fname</code>. 첨부 파일의 시스템 절대 경로 파일명
     */
    public String getSysFname() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_SQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_FNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.SYS_FNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getAttachId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getAttachSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAttachFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSysFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getAttachId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getAttachSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAttachFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSysFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value1(UInteger value) {
        setAttachId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value2(UInteger value) {
        setAttachSq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value3(String value) {
        setAttachFname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value4(String value) {
        setSysFname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord values(UInteger value1, UInteger value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbBoardFilelistTbRecord
     */
    public SbBoardFilelistTbRecord() {
        super(SbBoardFilelistTb.SB_BOARD_FILELIST_TB);
    }

    /**
     * Create a detached, initialised SbBoardFilelistTbRecord
     */
    public SbBoardFilelistTbRecord(UInteger attachId, UInteger attachSq, String attachFname, String sysFname) {
        super(SbBoardFilelistTb.SB_BOARD_FILELIST_TB);

        set(0, attachId);
        set(1, attachSq);
        set(2, attachFname);
        set(3, sysFname);
    }
}
