/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables.records;


import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.SbBoardFilelistTb;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbBoardFilelistTbRecord extends UpdatableRecordImpl<SbBoardFilelistTbRecord> implements Record5<UByte, UInteger, UInteger, String, String> {

    private static final long serialVersionUID = 1448799018;

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.board_id</code>.
     */
    public void setBoardId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.board_id</code>.
     */
    public UByte getBoardId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.board_no</code>.
     */
    public void setBoardNo(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.board_no</code>.
     */
    public UInteger getBoardNo() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.attach_sq</code>. 첨부 파일 순번
     */
    public void setAttachSq(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.attach_sq</code>. 첨부 파일 순번
     */
    public UInteger getAttachSq() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.attach_fname</code>. 첨부 파일 이름
     */
    public void setAttachFname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.attach_fname</code>. 첨부 파일 이름
     */
    public String getAttachFname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sb_db.sb_board_filelist_tb.sys_fname</code>. 첨부 파일의 시스템 절대 경로 파일명
     */
    public void setSysFname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_filelist_tb.sys_fname</code>. 첨부 파일의 시스템 절대 경로 파일명
     */
    public String getSysFname() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<UByte, UInteger, UInteger> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UByte, UInteger, UInteger, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UByte, UInteger, UInteger, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.BOARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.BOARD_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_SQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.ATTACH_FNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SbBoardFilelistTb.SB_BOARD_FILELIST_TB.SYS_FNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getBoardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getBoardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getAttachSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAttachFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSysFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getBoardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getBoardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getAttachSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAttachFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSysFname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value1(UByte value) {
        setBoardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value2(UInteger value) {
        setBoardNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value3(UInteger value) {
        setAttachSq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value4(String value) {
        setAttachFname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord value5(String value) {
        setSysFname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTbRecord values(UByte value1, UInteger value2, UInteger value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbBoardFilelistTbRecord
     */
    public SbBoardFilelistTbRecord() {
        super(SbBoardFilelistTb.SB_BOARD_FILELIST_TB);
    }

    /**
     * Create a detached, initialised SbBoardFilelistTbRecord
     */
    public SbBoardFilelistTbRecord(UByte boardId, UInteger boardNo, UInteger attachSq, String attachFname, String sysFname) {
        super(SbBoardFilelistTb.SB_BOARD_FILELIST_TB);

        set(0, boardId);
        set(1, boardNo);
        set(2, attachSq);
        set(3, attachFname);
        set(4, sysFname);
    }
}
