/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.SbBoardHistoryTb;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbBoardHistoryTbRecord extends UpdatableRecordImpl<SbBoardHistoryTbRecord> implements Record8<UByte, UInteger, UByte, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 1485327101;

    /**
     * Setter for <code>sb_db.sb_board_history_tb.board_id</code>.
     */
    public void setBoardId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_history_tb.board_id</code>.
     */
    public UByte getBoardId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_board_history_tb.board_no</code>.
     */
    public void setBoardNo(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_history_tb.board_no</code>.
     */
    public UInteger getBoardNo() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_board_history_tb.history_sq</code>. 히스토리 순서
     */
    public void setHistorySq(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_history_tb.history_sq</code>. 히스토리 순서
     */
    public UByte getHistorySq() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>sb_db.sb_board_history_tb.subject</code>.
     */
    public void setSubject(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_history_tb.subject</code>.
     */
    public String getSubject() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sb_db.sb_board_history_tb.content</code>.
     */
    public void setContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_history_tb.content</code>.
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sb_db.sb_board_history_tb.modifier_id</code>. 작성자
     */
    public void setModifierId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_history_tb.modifier_id</code>. 작성자
     */
    public String getModifierId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sb_db.sb_board_history_tb.ip</code>.
     */
    public void setIp(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_history_tb.ip</code>.
     */
    public String getIp() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sb_db.sb_board_history_tb.reg_dt</code>. 최초 작성일
     */
    public void setRegDt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>sb_db.sb_board_history_tb.reg_dt</code>. 최초 작성일
     */
    public Timestamp getRegDt() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<UByte, UInteger, UByte> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UByte, UInteger, UByte, String, String, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UByte, UInteger, UByte, String, String, String, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return SbBoardHistoryTb.SB_BOARD_HISTORY_TB.BOARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbBoardHistoryTb.SB_BOARD_HISTORY_TB.BOARD_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return SbBoardHistoryTb.SB_BOARD_HISTORY_TB.HISTORY_SQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SbBoardHistoryTb.SB_BOARD_HISTORY_TB.SUBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SbBoardHistoryTb.SB_BOARD_HISTORY_TB.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SbBoardHistoryTb.SB_BOARD_HISTORY_TB.MODIFIER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SbBoardHistoryTb.SB_BOARD_HISTORY_TB.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return SbBoardHistoryTb.SB_BOARD_HISTORY_TB.REG_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getBoardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getBoardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getHistorySq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getModifierId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getRegDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getBoardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getBoardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getHistorySq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getModifierId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getRegDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardHistoryTbRecord value1(UByte value) {
        setBoardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardHistoryTbRecord value2(UInteger value) {
        setBoardNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardHistoryTbRecord value3(UByte value) {
        setHistorySq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardHistoryTbRecord value4(String value) {
        setSubject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardHistoryTbRecord value5(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardHistoryTbRecord value6(String value) {
        setModifierId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardHistoryTbRecord value7(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardHistoryTbRecord value8(Timestamp value) {
        setRegDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardHistoryTbRecord values(UByte value1, UInteger value2, UByte value3, String value4, String value5, String value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbBoardHistoryTbRecord
     */
    public SbBoardHistoryTbRecord() {
        super(SbBoardHistoryTb.SB_BOARD_HISTORY_TB);
    }

    /**
     * Create a detached, initialised SbBoardHistoryTbRecord
     */
    public SbBoardHistoryTbRecord(UByte boardId, UInteger boardNo, UByte historySq, String subject, String content, String modifierId, String ip, Timestamp regDt) {
        super(SbBoardHistoryTb.SB_BOARD_HISTORY_TB);

        set(0, boardId);
        set(1, boardNo);
        set(2, historySq);
        set(3, subject);
        set(4, content);
        set(5, modifierId);
        set(6, ip);
        set(7, regDt);
    }
}
