/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.SbGroupTb;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbGroupTbRecord extends UpdatableRecordImpl<SbGroupTbRecord> implements Record3<Byte, String, Timestamp> {

    private static final long serialVersionUID = -282032227;

    /**
     * Setter for <code>SB_DB.SB_GROUP_TB.group_id</code>.
     */
    public void setGroupId(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>SB_DB.SB_GROUP_TB.group_id</code>.
     */
    public Byte getGroupId() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>SB_DB.SB_GROUP_TB.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SB_DB.SB_GROUP_TB.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SB_DB.SB_GROUP_TB.reg_dt</code>.
     */
    public void setRegDt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>SB_DB.SB_GROUP_TB.reg_dt</code>.
     */
    public Timestamp getRegDt() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Byte, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Byte, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Byte, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field1() {
        return SbGroupTb.SB_GROUP_TB.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SbGroupTb.SB_GROUP_TB.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return SbGroupTb.SB_GROUP_TB.REG_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getRegDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getRegDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbGroupTbRecord value1(Byte value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbGroupTbRecord value2(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbGroupTbRecord value3(Timestamp value) {
        setRegDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbGroupTbRecord values(Byte value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbGroupTbRecord
     */
    public SbGroupTbRecord() {
        super(SbGroupTb.SB_GROUP_TB);
    }

    /**
     * Create a detached, initialised SbGroupTbRecord
     */
    public SbGroupTbRecord(Byte groupId, String userId, Timestamp regDt) {
        super(SbGroupTb.SB_GROUP_TB);

        set(0, groupId);
        set(1, userId);
        set(2, regDt);
    }
}
