/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.SbPwdSerarchReqTb;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbPwdSerarchReqTbRecord extends UpdatableRecordImpl<SbPwdSerarchReqTbRecord> implements Record5<String, UByte, UByte, String, Timestamp> {

    private static final long serialVersionUID = 840974184;

    /**
     * Setter for <code>sb_db.sb_pwd_serarch_req_tb.user_id</code>. 사용자 아이디
     */
    public void setUserId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_pwd_serarch_req_tb.user_id</code>. 사용자 아이디
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_pwd_serarch_req_tb.fail_cnt</code>. 비밀 인증 값 실패 횟수
     */
    public void setFailCnt(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_pwd_serarch_req_tb.fail_cnt</code>. 비밀 인증 값 실패 횟수
     */
    public UByte getFailCnt() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_pwd_serarch_req_tb.retry_cnt</code>. 비밀번호 찾기 재시도 횟수
     */
    public void setRetryCnt(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_pwd_serarch_req_tb.retry_cnt</code>. 비밀번호 찾기 재시도 횟수
     */
    public UByte getRetryCnt() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>sb_db.sb_pwd_serarch_req_tb.last_secret_auth_value</code>. 마지막 비밀 인증 값, 비밀번호 찾기 요청은 최대 횟수까지 가능하며 그때마다 '비밀 인증 값' 과 '비밀 번호 찾기 요청일' 이 변경된다
     */
    public void setLastSecretAuthValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sb_db.sb_pwd_serarch_req_tb.last_secret_auth_value</code>. 마지막 비밀 인증 값, 비밀번호 찾기 요청은 최대 횟수까지 가능하며 그때마다 '비밀 인증 값' 과 '비밀 번호 찾기 요청일' 이 변경된다
     */
    public String getLastSecretAuthValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sb_db.sb_pwd_serarch_req_tb.last_req_dt</code>. 마지막 비밀번호 찾기 요청일, 비밀번호 찾기 요청은 최대 횟수까지 가능하며 그때마다 '비밀 인증 값' 과 '비밀 번호 찾기 요청일' 이 변경된다
     */
    public void setLastReqDt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>sb_db.sb_pwd_serarch_req_tb.last_req_dt</code>. 마지막 비밀번호 찾기 요청일, 비밀번호 찾기 요청은 최대 횟수까지 가능하며 그때마다 '비밀 인증 값' 과 '비밀 번호 찾기 요청일' 이 변경된다
     */
    public Timestamp getLastReqDt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, UByte, UByte, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, UByte, UByte, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SbPwdSerarchReqTb.SB_PWD_SERARCH_REQ_TB.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field2() {
        return SbPwdSerarchReqTb.SB_PWD_SERARCH_REQ_TB.FAIL_CNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return SbPwdSerarchReqTb.SB_PWD_SERARCH_REQ_TB.RETRY_CNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SbPwdSerarchReqTb.SB_PWD_SERARCH_REQ_TB.LAST_SECRET_AUTH_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return SbPwdSerarchReqTb.SB_PWD_SERARCH_REQ_TB.LAST_REQ_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component2() {
        return getFailCnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getRetryCnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLastSecretAuthValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastReqDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value2() {
        return getFailCnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getRetryCnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLastSecretAuthValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastReqDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbPwdSerarchReqTbRecord value1(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbPwdSerarchReqTbRecord value2(UByte value) {
        setFailCnt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbPwdSerarchReqTbRecord value3(UByte value) {
        setRetryCnt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbPwdSerarchReqTbRecord value4(String value) {
        setLastSecretAuthValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbPwdSerarchReqTbRecord value5(Timestamp value) {
        setLastReqDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbPwdSerarchReqTbRecord values(String value1, UByte value2, UByte value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbPwdSerarchReqTbRecord
     */
    public SbPwdSerarchReqTbRecord() {
        super(SbPwdSerarchReqTb.SB_PWD_SERARCH_REQ_TB);
    }

    /**
     * Create a detached, initialised SbPwdSerarchReqTbRecord
     */
    public SbPwdSerarchReqTbRecord(String userId, UByte failCnt, UByte retryCnt, String lastSecretAuthValue, Timestamp lastReqDt) {
        super(SbPwdSerarchReqTb.SB_PWD_SERARCH_REQ_TB);

        set(0, userId);
        set(1, failCnt);
        set(2, retryCnt);
        set(3, lastSecretAuthValue);
        set(4, lastReqDt);
    }
}
