/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables.records;


import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.SbSeqTb;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbSeqTbRecord extends UpdatableRecordImpl<SbSeqTbRecord> implements Record3<UByte, UInteger, String> {

    private static final long serialVersionUID = -2086302144;

    /**
     * Setter for <code>sb_db.sb_seq_tb.sq_id</code>. 시퀀스 식별자, 0:메뉴, 1:업로드 파일 이름 시퀀스, 2:공지게시판 시퀀스, 3:자유게시판시퀀스, 4:FAQ시퀀스
     */
    public void setSqId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_seq_tb.sq_id</code>. 시퀀스 식별자, 0:메뉴, 1:업로드 파일 이름 시퀀스, 2:공지게시판 시퀀스, 3:자유게시판시퀀스, 4:FAQ시퀀스
     */
    public UByte getSqId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_seq_tb.sq_value</code>. 시퀀스 값
     */
    public void setSqValue(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_seq_tb.sq_value</code>. 시퀀스 값
     */
    public UInteger getSqValue() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_seq_tb.sq_name</code>. 시퀀스 이름
     */
    public void setSqName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_seq_tb.sq_name</code>. 시퀀스 이름
     */
    public String getSqName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UByte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UByte, UInteger, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UByte, UInteger, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return SbSeqTb.SB_SEQ_TB.SQ_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbSeqTb.SB_SEQ_TB.SQ_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SbSeqTb.SB_SEQ_TB.SQ_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getSqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getSqValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSqName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getSqId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getSqValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSqName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSeqTbRecord value1(UByte value) {
        setSqId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSeqTbRecord value2(UInteger value) {
        setSqValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSeqTbRecord value3(String value) {
        setSqName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSeqTbRecord values(UByte value1, UInteger value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbSeqTbRecord
     */
    public SbSeqTbRecord() {
        super(SbSeqTb.SB_SEQ_TB);
    }

    /**
     * Create a detached, initialised SbSeqTbRecord
     */
    public SbSeqTbRecord(UByte sqId, UInteger sqValue, String sqName) {
        super(SbSeqTb.SB_SEQ_TB);

        set(0, sqId);
        set(1, sqValue);
        set(2, sqName);
    }
}
