/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.SbSiteLogTb;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbSiteLogTbRecord extends UpdatableRecordImpl<SbSiteLogTbRecord> implements Record6<String, UInteger, String, String, Timestamp, String> {

    private static final long serialVersionUID = -253471470;

    /**
     * Setter for <code>sb_db.sb_site_log_tb.yyyymmdd</code>. 로그 날짜, yyyyMMdd 형태의 8자리 년월일 문자
     */
    public void setYyyymmdd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_site_log_tb.yyyymmdd</code>. 로그 날짜, yyyyMMdd 형태의 8자리 년월일 문자
     */
    public String getYyyymmdd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_site_log_tb.day_log_sq</code>. 일일 로그 순번
     */
    public void setDayLogSq(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_site_log_tb.day_log_sq</code>. 일일 로그 순번
     */
    public UInteger getDayLogSq() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_site_log_tb.user_id</code>. 사용자 아이디
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_site_log_tb.user_id</code>. 사용자 아이디
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sb_db.sb_site_log_tb.log_txt</code>. 로그 내용, 로그로 남기는 내용 (1) 회원 가입, (2) 회원 탈퇴, (3) 사용자 차단, (4) 사용자 차단 해제, (5) 게시글 차단, (6) 게시글 차단 해제,  (7) 관리자 로그인
     */
    public void setLogTxt(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sb_db.sb_site_log_tb.log_txt</code>. 로그 내용, 로그로 남기는 내용 (1) 회원 가입, (2) 회원 탈퇴, (3) 사용자 차단, (4) 사용자 차단 해제, (5) 게시글 차단, (6) 게시글 차단 해제,  (7) 관리자 로그인
     */
    public String getLogTxt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sb_db.sb_site_log_tb.reg_dt</code>.
     */
    public void setRegDt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>sb_db.sb_site_log_tb.reg_dt</code>.
     */
    public Timestamp getRegDt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>sb_db.sb_site_log_tb.ip</code>.
     */
    public void setIp(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sb_db.sb_site_log_tb.ip</code>.
     */
    public String getIp() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, UInteger, String, String, Timestamp, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, UInteger, String, String, Timestamp, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SbSiteLogTb.SB_SITE_LOG_TB.YYYYMMDD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return SbSiteLogTb.SB_SITE_LOG_TB.DAY_LOG_SQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SbSiteLogTb.SB_SITE_LOG_TB.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SbSiteLogTb.SB_SITE_LOG_TB.LOG_TXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return SbSiteLogTb.SB_SITE_LOG_TB.REG_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SbSiteLogTb.SB_SITE_LOG_TB.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getYyyymmdd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getDayLogSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLogTxt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getRegDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getYyyymmdd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getDayLogSq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLogTxt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getRegDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSiteLogTbRecord value1(String value) {
        setYyyymmdd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSiteLogTbRecord value2(UInteger value) {
        setDayLogSq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSiteLogTbRecord value3(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSiteLogTbRecord value4(String value) {
        setLogTxt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSiteLogTbRecord value5(Timestamp value) {
        setRegDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSiteLogTbRecord value6(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbSiteLogTbRecord values(String value1, UInteger value2, String value3, String value4, Timestamp value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbSiteLogTbRecord
     */
    public SbSiteLogTbRecord() {
        super(SbSiteLogTb.SB_SITE_LOG_TB);
    }

    /**
     * Create a detached, initialised SbSiteLogTbRecord
     */
    public SbSiteLogTbRecord(String yyyymmdd, UInteger dayLogSq, String userId, String logTxt, Timestamp regDt, String ip) {
        super(SbSiteLogTb.SB_SITE_LOG_TB);

        set(0, yyyymmdd);
        set(1, dayLogSq);
        set(2, userId);
        set(3, logTxt);
        set(4, regDt);
        set(5, ip);
    }
}
