/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.tables.SbUserActionHistoryTb;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbUserActionHistoryTbRecord extends UpdatableRecordImpl<SbUserActionHistoryTbRecord> implements Record5<UInteger, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1208101455;

    /**
     * Setter for <code>sb_db.sb_user_action_history_tb.no</code>.
     */
    public void setNo(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>sb_db.sb_user_action_history_tb.no</code>.
     */
    public UInteger getNo() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>sb_db.sb_user_action_history_tb.user_id</code>. 사용자 아이디
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sb_db.sb_user_action_history_tb.user_id</code>. 사용자 아이디
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sb_db.sb_user_action_history_tb.input_message_id</code>. 입력 메시지 식별자
     */
    public void setInputMessageId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sb_db.sb_user_action_history_tb.input_message_id</code>. 입력 메시지 식별자
     */
    public String getInputMessageId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sb_db.sb_user_action_history_tb.input_message</code>. 입력 메시지 내용
     */
    public void setInputMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sb_db.sb_user_action_history_tb.input_message</code>. 입력 메시지 내용
     */
    public String getInputMessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sb_db.sb_user_action_history_tb.reg_dt</code>.
     */
    public void setRegDt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>sb_db.sb_user_action_history_tb.reg_dt</code>.
     */
    public Timestamp getRegDt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return SbUserActionHistoryTb.SB_USER_ACTION_HISTORY_TB.NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SbUserActionHistoryTb.SB_USER_ACTION_HISTORY_TB.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SbUserActionHistoryTb.SB_USER_ACTION_HISTORY_TB.INPUT_MESSAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SbUserActionHistoryTb.SB_USER_ACTION_HISTORY_TB.INPUT_MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return SbUserActionHistoryTb.SB_USER_ACTION_HISTORY_TB.REG_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getInputMessageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getInputMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getRegDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getInputMessageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInputMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getRegDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUserActionHistoryTbRecord value1(UInteger value) {
        setNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUserActionHistoryTbRecord value2(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUserActionHistoryTbRecord value3(String value) {
        setInputMessageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUserActionHistoryTbRecord value4(String value) {
        setInputMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUserActionHistoryTbRecord value5(Timestamp value) {
        setRegDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUserActionHistoryTbRecord values(UInteger value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SbUserActionHistoryTbRecord
     */
    public SbUserActionHistoryTbRecord() {
        super(SbUserActionHistoryTb.SB_USER_ACTION_HISTORY_TB);
    }

    /**
     * Create a detached, initialised SbUserActionHistoryTbRecord
     */
    public SbUserActionHistoryTbRecord(UInteger no, String userId, String inputMessageId, String inputMessage, Timestamp regDt) {
        super(SbUserActionHistoryTb.SB_USER_ACTION_HISTORY_TB);

        set(0, no);
        set(1, userId);
        set(2, inputMessageId);
        set(3, inputMessage);
        set(4, regDt);
    }
}
