/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.Indexes;
import kr.pe.codda.impl.jooq.Keys;
import kr.pe.codda.impl.jooq.SbDb;
import kr.pe.codda.impl.jooq.tables.records.SbBoardFileinfoTbRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbBoardFileinfoTb extends TableImpl<SbBoardFileinfoTbRecord> {

    private static final long serialVersionUID = -279229303;

    /**
     * The reference instance of <code>sb_db.sb_board_fileinfo_tb</code>
     */
    public static final SbBoardFileinfoTb SB_BOARD_FILEINFO_TB = new SbBoardFileinfoTb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SbBoardFileinfoTbRecord> getRecordType() {
        return SbBoardFileinfoTbRecord.class;
    }

    /**
     * The column <code>sb_db.sb_board_fileinfo_tb.attach_id</code>. 업로드 식별자, 자동증가
     */
    public final TableField<SbBoardFileinfoTbRecord, UInteger> ATTACH_ID = createField("attach_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "업로드 식별자, 자동증가");

    /**
     * The column <code>sb_db.sb_board_fileinfo_tb.owner_id</code>. 첨부 파일 등록자 아이디
     */
    public final TableField<SbBoardFileinfoTbRecord, String> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "첨부 파일 등록자 아이디");

    /**
     * The column <code>sb_db.sb_board_fileinfo_tb.ip</code>. 첨부 파일 등록자 IP 주소
     */
    public final TableField<SbBoardFileinfoTbRecord, String> IP = createField("ip", org.jooq.impl.SQLDataType.VARCHAR(15), this, "첨부 파일 등록자 IP 주소");

    /**
     * The column <code>sb_db.sb_board_fileinfo_tb.reg_dt</code>. 최초 등록일
     */
    public final TableField<SbBoardFileinfoTbRecord, Timestamp> REG_DT = createField("reg_dt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "최초 등록일");

    /**
     * The column <code>sb_db.sb_board_fileinfo_tb.mod_dt</code>. 최근 수정일
     */
    public final TableField<SbBoardFileinfoTbRecord, Timestamp> MOD_DT = createField("mod_dt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "최근 수정일");

    /**
     * Create a <code>sb_db.sb_board_fileinfo_tb</code> table reference
     */
    public SbBoardFileinfoTb() {
        this(DSL.name("sb_board_fileinfo_tb"), null);
    }
    
    /**
     * Create an aliased <code>sb_db.sb_board_fileinfo_tb</code> table reference
     */
    public SbBoardFileinfoTb(String alias) {
        this(DSL.name(alias), SB_BOARD_FILEINFO_TB);
    }

    /**
     * Create an aliased <code>sb_db.sb_board_fileinfo_tb</code> table reference
     */
    public SbBoardFileinfoTb(Name alias) {
        this(alias, SB_BOARD_FILEINFO_TB);
    }

    private SbBoardFileinfoTb(Name alias, Table<SbBoardFileinfoTbRecord> aliased) {
        this(alias, aliased, null);
    }

    private SbBoardFileinfoTb(Name alias, Table<SbBoardFileinfoTbRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SbDb.SB_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SB_BOARD_FILEINFO_TB_PRIMARY, Indexes.SB_BOARD_FILEINFO_TB_SB_BOARD_FILEINFO_FK1_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SbBoardFileinfoTbRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_SB_BOARD_FILEINFO_TB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SbBoardFileinfoTbRecord> getPrimaryKey() {
        return Keys.KEY_SB_BOARD_FILEINFO_TB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SbBoardFileinfoTbRecord>> getKeys() {
        return Arrays.<UniqueKey<SbBoardFileinfoTbRecord>>asList(Keys.KEY_SB_BOARD_FILEINFO_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SbBoardFileinfoTbRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SbBoardFileinfoTbRecord, ?>>asList(Keys.SB_BOARD_FILEINFO_FK1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFileinfoTb as(String alias) {
        return new SbBoardFileinfoTb(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFileinfoTb as(Name alias) {
        return new SbBoardFileinfoTb(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SbBoardFileinfoTb rename(String name) {
        return new SbBoardFileinfoTb(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SbBoardFileinfoTb rename(Name name) {
        return new SbBoardFileinfoTb(name, null);
    }
}
