/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.Indexes;
import kr.pe.codda.impl.jooq.Keys;
import kr.pe.codda.impl.jooq.SbDb;
import kr.pe.codda.impl.jooq.tables.records.SbBoardFilelistTbRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbBoardFilelistTb extends TableImpl<SbBoardFilelistTbRecord> {

    private static final long serialVersionUID = -510964487;

    /**
     * The reference instance of <code>sb_db.sb_board_filelist_tb</code>
     */
    public static final SbBoardFilelistTb SB_BOARD_FILELIST_TB = new SbBoardFilelistTb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SbBoardFilelistTbRecord> getRecordType() {
        return SbBoardFilelistTbRecord.class;
    }

    /**
     * The column <code>sb_db.sb_board_filelist_tb.board_id</code>.
     */
    public final TableField<SbBoardFilelistTbRecord, UByte> BOARD_ID = createField("board_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>sb_db.sb_board_filelist_tb.board_no</code>.
     */
    public final TableField<SbBoardFilelistTbRecord, UInteger> BOARD_NO = createField("board_no", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>sb_db.sb_board_filelist_tb.attached_file_sq</code>. 첨부 파일 순번
     */
    public final TableField<SbBoardFilelistTbRecord, UByte> ATTACHED_FILE_SQ = createField("attached_file_sq", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "첨부 파일 순번");

    /**
     * The column <code>sb_db.sb_board_filelist_tb.attached_fname</code>. 첨부 파일 이름
     */
    public final TableField<SbBoardFilelistTbRecord, String> ATTACHED_FNAME = createField("attached_fname", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "첨부 파일 이름");

    /**
     * Create a <code>sb_db.sb_board_filelist_tb</code> table reference
     */
    public SbBoardFilelistTb() {
        this(DSL.name("sb_board_filelist_tb"), null);
    }

    /**
     * Create an aliased <code>sb_db.sb_board_filelist_tb</code> table reference
     */
    public SbBoardFilelistTb(String alias) {
        this(DSL.name(alias), SB_BOARD_FILELIST_TB);
    }

    /**
     * Create an aliased <code>sb_db.sb_board_filelist_tb</code> table reference
     */
    public SbBoardFilelistTb(Name alias) {
        this(alias, SB_BOARD_FILELIST_TB);
    }

    private SbBoardFilelistTb(Name alias, Table<SbBoardFilelistTbRecord> aliased) {
        this(alias, aliased, null);
    }

    private SbBoardFilelistTb(Name alias, Table<SbBoardFilelistTbRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SbDb.SB_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SB_BOARD_FILELIST_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SbBoardFilelistTbRecord> getPrimaryKey() {
        return Keys.KEY_SB_BOARD_FILELIST_TB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SbBoardFilelistTbRecord>> getKeys() {
        return Arrays.<UniqueKey<SbBoardFilelistTbRecord>>asList(Keys.KEY_SB_BOARD_FILELIST_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SbBoardFilelistTbRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SbBoardFilelistTbRecord, ?>>asList(Keys.SB_BOARD_FILELIST_FK1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTb as(String alias) {
        return new SbBoardFilelistTb(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbBoardFilelistTb as(Name alias) {
        return new SbBoardFilelistTb(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SbBoardFilelistTb rename(String name) {
        return new SbBoardFilelistTb(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SbBoardFilelistTb rename(Name name) {
        return new SbBoardFilelistTb(name, null);
    }
}
