/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.Indexes;
import kr.pe.codda.impl.jooq.Keys;
import kr.pe.codda.impl.jooq.SbDb;
import kr.pe.codda.impl.jooq.tables.records.SbGroupInfoTbRecord;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbGroupInfoTb extends TableImpl<SbGroupInfoTbRecord> {

    private static final long serialVersionUID = 1645600351;

    /**
     * The reference instance of <code>sb_db.sb_group_info_tb</code>
     */
    public static final SbGroupInfoTb SB_GROUP_INFO_TB = new SbGroupInfoTb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SbGroupInfoTbRecord> getRecordType() {
        return SbGroupInfoTbRecord.class;
    }

    /**
     * The column <code>sb_db.sb_group_info_tb.group_id</code>. 그룹 식별자
     */
    public final TableField<SbGroupInfoTbRecord, Byte> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "그룹 식별자");

    /**
     * The column <code>sb_db.sb_group_info_tb.group_name</code>.
     */
    public final TableField<SbGroupInfoTbRecord, String> GROUP_NAME = createField("group_name", org.jooq.impl.SQLDataType.VARCHAR(45).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sb_db.sb_group_info_tb.group_info</code>.
     */
    public final TableField<SbGroupInfoTbRecord, String> GROUP_INFO = createField("group_info", org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.CLOB)), this, "");

    /**
     * Create a <code>sb_db.sb_group_info_tb</code> table reference
     */
    public SbGroupInfoTb() {
        this(DSL.name("sb_group_info_tb"), null);
    }

    /**
     * Create an aliased <code>sb_db.sb_group_info_tb</code> table reference
     */
    public SbGroupInfoTb(String alias) {
        this(DSL.name(alias), SB_GROUP_INFO_TB);
    }

    /**
     * Create an aliased <code>sb_db.sb_group_info_tb</code> table reference
     */
    public SbGroupInfoTb(Name alias) {
        this(alias, SB_GROUP_INFO_TB);
    }

    private SbGroupInfoTb(Name alias, Table<SbGroupInfoTbRecord> aliased) {
        this(alias, aliased, null);
    }

    private SbGroupInfoTb(Name alias, Table<SbGroupInfoTbRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SbDb.SB_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SB_GROUP_INFO_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SbGroupInfoTbRecord> getPrimaryKey() {
        return Keys.KEY_SB_GROUP_INFO_TB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SbGroupInfoTbRecord>> getKeys() {
        return Arrays.<UniqueKey<SbGroupInfoTbRecord>>asList(Keys.KEY_SB_GROUP_INFO_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbGroupInfoTb as(String alias) {
        return new SbGroupInfoTb(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbGroupInfoTb as(Name alias) {
        return new SbGroupInfoTb(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SbGroupInfoTb rename(String name) {
        return new SbGroupInfoTb(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SbGroupInfoTb rename(Name name) {
        return new SbGroupInfoTb(name, null);
    }
}
