/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.Indexes;
import kr.pe.codda.impl.jooq.Keys;
import kr.pe.codda.impl.jooq.SbDb;
import kr.pe.codda.impl.jooq.tables.records.SbPwdSerarchReqTbRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbPwdSerarchReqTb extends TableImpl<SbPwdSerarchReqTbRecord> {

    private static final long serialVersionUID = -405940519;

    /**
     * The reference instance of <code>sb_db.sb_pwd_serarch_req_tb</code>
     */
    public static final SbPwdSerarchReqTb SB_PWD_SERARCH_REQ_TB = new SbPwdSerarchReqTb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SbPwdSerarchReqTbRecord> getRecordType() {
        return SbPwdSerarchReqTbRecord.class;
    }

    /**
     * The column <code>sb_db.sb_pwd_serarch_req_tb.user_id</code>. 사용자 아이디
     */
    public final TableField<SbPwdSerarchReqTbRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "사용자 아이디");

    /**
     * The column <code>sb_db.sb_pwd_serarch_req_tb.fail_cnt</code>. 비밀 인증 값 실패 횟수
     */
    public final TableField<SbPwdSerarchReqTbRecord, UByte> FAIL_CNT = createField("fail_cnt", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "비밀 인증 값 실패 횟수");

    /**
     * The column <code>sb_db.sb_pwd_serarch_req_tb.retry_cnt</code>. 비밀번호 찾기 재시도 횟수
     */
    public final TableField<SbPwdSerarchReqTbRecord, UByte> RETRY_CNT = createField("retry_cnt", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "비밀번호 찾기 재시도 횟수");

    /**
     * The column <code>sb_db.sb_pwd_serarch_req_tb.last_secret_auth_value</code>. 마지막 비밀 인증 값, 비밀번호 찾기 요청은 최대 횟수까지 가능하며 그때마다 '비밀 인증 값' 과 '비밀 번호 찾기 요청일' 이 변경된다
     */
    public final TableField<SbPwdSerarchReqTbRecord, String> LAST_SECRET_AUTH_VALUE = createField("last_secret_auth_value", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "마지막 비밀 인증 값, 비밀번호 찾기 요청은 최대 횟수까지 가능하며 그때마다 '비밀 인증 값' 과 '비밀 번호 찾기 요청일' 이 변경된다");

    /**
     * The column <code>sb_db.sb_pwd_serarch_req_tb.last_req_dt</code>. 마지막 비밀번호 찾기 요청일, 비밀번호 찾기 요청은 최대 횟수까지 가능하며 그때마다 '비밀 인증 값' 과 '비밀 번호 찾기 요청일' 이 변경된다
     */
    public final TableField<SbPwdSerarchReqTbRecord, Timestamp> LAST_REQ_DT = createField("last_req_dt", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "마지막 비밀번호 찾기 요청일, 비밀번호 찾기 요청은 최대 횟수까지 가능하며 그때마다 '비밀 인증 값' 과 '비밀 번호 찾기 요청일' 이 변경된다");

    /**
     * Create a <code>sb_db.sb_pwd_serarch_req_tb</code> table reference
     */
    public SbPwdSerarchReqTb() {
        this(DSL.name("sb_pwd_serarch_req_tb"), null);
    }

    /**
     * Create an aliased <code>sb_db.sb_pwd_serarch_req_tb</code> table reference
     */
    public SbPwdSerarchReqTb(String alias) {
        this(DSL.name(alias), SB_PWD_SERARCH_REQ_TB);
    }

    /**
     * Create an aliased <code>sb_db.sb_pwd_serarch_req_tb</code> table reference
     */
    public SbPwdSerarchReqTb(Name alias) {
        this(alias, SB_PWD_SERARCH_REQ_TB);
    }

    private SbPwdSerarchReqTb(Name alias, Table<SbPwdSerarchReqTbRecord> aliased) {
        this(alias, aliased, null);
    }

    private SbPwdSerarchReqTb(Name alias, Table<SbPwdSerarchReqTbRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SbDb.SB_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SB_PWD_SERARCH_REQ_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SbPwdSerarchReqTbRecord> getPrimaryKey() {
        return Keys.KEY_SB_PWD_SERARCH_REQ_TB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SbPwdSerarchReqTbRecord>> getKeys() {
        return Arrays.<UniqueKey<SbPwdSerarchReqTbRecord>>asList(Keys.KEY_SB_PWD_SERARCH_REQ_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SbPwdSerarchReqTbRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SbPwdSerarchReqTbRecord, ?>>asList(Keys.PWD_SEARCH_REQ_FK1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbPwdSerarchReqTb as(String alias) {
        return new SbPwdSerarchReqTb(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbPwdSerarchReqTb as(Name alias) {
        return new SbPwdSerarchReqTb(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SbPwdSerarchReqTb rename(String name) {
        return new SbPwdSerarchReqTb(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SbPwdSerarchReqTb rename(Name name) {
        return new SbPwdSerarchReqTb(name, null);
    }
}
