/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.impl.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import kr.pe.codda.impl.jooq.Indexes;
import kr.pe.codda.impl.jooq.Keys;
import kr.pe.codda.impl.jooq.SbDb;
import kr.pe.codda.impl.jooq.tables.records.SbUserActionHistoryTbRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SbUserActionHistoryTb extends TableImpl<SbUserActionHistoryTbRecord> {

    private static final long serialVersionUID = 1612107334;

    /**
     * The reference instance of <code>sb_db.sb_user_action_history_tb</code>
     */
    public static final SbUserActionHistoryTb SB_USER_ACTION_HISTORY_TB = new SbUserActionHistoryTb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SbUserActionHistoryTbRecord> getRecordType() {
        return SbUserActionHistoryTbRecord.class;
    }

    /**
     * The column <code>sb_db.sb_user_action_history_tb.no</code>.
     */
    public final TableField<SbUserActionHistoryTbRecord, UInteger> NO = createField("no", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>sb_db.sb_user_action_history_tb.user_id</code>. 사용자 아이디
     */
    public final TableField<SbUserActionHistoryTbRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "사용자 아이디");

    /**
     * The column <code>sb_db.sb_user_action_history_tb.input_message_id</code>. 입력 메시지 식별자
     */
    public final TableField<SbUserActionHistoryTbRecord, String> INPUT_MESSAGE_ID = createField("input_message_id", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "입력 메시지 식별자");

    /**
     * The column <code>sb_db.sb_user_action_history_tb.input_message</code>. 입력 메시지 내용
     */
    public final TableField<SbUserActionHistoryTbRecord, String> INPUT_MESSAGE = createField("input_message", org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.CLOB)), this, "입력 메시지 내용");

    /**
     * The column <code>sb_db.sb_user_action_history_tb.reg_dt</code>.
     */
    public final TableField<SbUserActionHistoryTbRecord, Timestamp> REG_DT = createField("reg_dt", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>sb_db.sb_user_action_history_tb</code> table reference
     */
    public SbUserActionHistoryTb() {
        this(DSL.name("sb_user_action_history_tb"), null);
    }

    /**
     * Create an aliased <code>sb_db.sb_user_action_history_tb</code> table reference
     */
    public SbUserActionHistoryTb(String alias) {
        this(DSL.name(alias), SB_USER_ACTION_HISTORY_TB);
    }

    /**
     * Create an aliased <code>sb_db.sb_user_action_history_tb</code> table reference
     */
    public SbUserActionHistoryTb(Name alias) {
        this(alias, SB_USER_ACTION_HISTORY_TB);
    }

    private SbUserActionHistoryTb(Name alias, Table<SbUserActionHistoryTbRecord> aliased) {
        this(alias, aliased, null);
    }

    private SbUserActionHistoryTb(Name alias, Table<SbUserActionHistoryTbRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SbDb.SB_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SB_USER_ACTION_HISTORY_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SbUserActionHistoryTbRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_SB_USER_ACTION_HISTORY_TB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SbUserActionHistoryTbRecord> getPrimaryKey() {
        return Keys.KEY_SB_USER_ACTION_HISTORY_TB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SbUserActionHistoryTbRecord>> getKeys() {
        return Arrays.<UniqueKey<SbUserActionHistoryTbRecord>>asList(Keys.KEY_SB_USER_ACTION_HISTORY_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUserActionHistoryTb as(String alias) {
        return new SbUserActionHistoryTb(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SbUserActionHistoryTb as(Name alias) {
        return new SbUserActionHistoryTb(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SbUserActionHistoryTb rename(String name) {
        return new SbUserActionHistoryTb(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SbUserActionHistoryTb rename(Name name) {
        return new SbUserActionHistoryTb(name, null);
    }
}
