/*
 * This file is generated by jOOQ.
*/
package kr.pe.codda.jooq;


import javax.annotation.Generated;

import kr.pe.codda.jooq.tables.SbAccountSerarchTb;
import kr.pe.codda.jooq.tables.SbBoardFilelistTb;
import kr.pe.codda.jooq.tables.SbBoardHistoryTb;
import kr.pe.codda.jooq.tables.SbBoardInfoTb;
import kr.pe.codda.jooq.tables.SbBoardTb;
import kr.pe.codda.jooq.tables.SbBoardVoteTb;
import kr.pe.codda.jooq.tables.SbMemberActivityHistoryTb;
import kr.pe.codda.jooq.tables.SbMemberTb;
import kr.pe.codda.jooq.tables.SbSeqTb;
import kr.pe.codda.jooq.tables.SbSiteLogTb;
import kr.pe.codda.jooq.tables.SbSitemenuTb;


/**
 * Convenience access to all tables in sb_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sb_db.sb_account_serarch_tb</code>.
     */
    public static final SbAccountSerarchTb SB_ACCOUNT_SERARCH_TB = kr.pe.codda.jooq.tables.SbAccountSerarchTb.SB_ACCOUNT_SERARCH_TB;

    /**
     * The table <code>sb_db.sb_board_filelist_tb</code>.
     */
    public static final SbBoardFilelistTb SB_BOARD_FILELIST_TB = kr.pe.codda.jooq.tables.SbBoardFilelistTb.SB_BOARD_FILELIST_TB;

    /**
     * The table <code>sb_db.sb_board_history_tb</code>.
     */
    public static final SbBoardHistoryTb SB_BOARD_HISTORY_TB = kr.pe.codda.jooq.tables.SbBoardHistoryTb.SB_BOARD_HISTORY_TB;

    /**
     * The table <code>sb_db.sb_board_info_tb</code>.
     */
    public static final SbBoardInfoTb SB_BOARD_INFO_TB = kr.pe.codda.jooq.tables.SbBoardInfoTb.SB_BOARD_INFO_TB;

    /**
     * The table <code>sb_db.sb_board_tb</code>.
     */
    public static final SbBoardTb SB_BOARD_TB = kr.pe.codda.jooq.tables.SbBoardTb.SB_BOARD_TB;

    /**
     * The table <code>sb_db.sb_board_vote_tb</code>.
     */
    public static final SbBoardVoteTb SB_BOARD_VOTE_TB = kr.pe.codda.jooq.tables.SbBoardVoteTb.SB_BOARD_VOTE_TB;

    /**
     * The table <code>sb_db.sb_member_activity_history_tb</code>.
     */
    public static final SbMemberActivityHistoryTb SB_MEMBER_ACTIVITY_HISTORY_TB = kr.pe.codda.jooq.tables.SbMemberActivityHistoryTb.SB_MEMBER_ACTIVITY_HISTORY_TB;

    /**
     * The table <code>sb_db.sb_member_tb</code>.
     */
    public static final SbMemberTb SB_MEMBER_TB = kr.pe.codda.jooq.tables.SbMemberTb.SB_MEMBER_TB;

    /**
     * The table <code>sb_db.sb_seq_tb</code>.
     */
    public static final SbSeqTb SB_SEQ_TB = kr.pe.codda.jooq.tables.SbSeqTb.SB_SEQ_TB;

    /**
     * The table <code>sb_db.sb_sitemenu_tb</code>.
     */
    public static final SbSitemenuTb SB_SITEMENU_TB = kr.pe.codda.jooq.tables.SbSitemenuTb.SB_SITEMENU_TB;

    /**
     * The table <code>sb_db.sb_site_log_tb</code>.
     */
    public static final SbSiteLogTb SB_SITE_LOG_TB = kr.pe.codda.jooq.tables.SbSiteLogTb.SB_SITE_LOG_TB;
}
